### ISSUE TITLE
Enable Authentication via REST

### ISSUE THREAD

**Issue by xBau** [NeosIT/active-directory-integration2#101]
We are using wordpress only as a CMS for an electron desktop app.

Login via wp-login.php works like a charm but login via our app using JWT auth only works if the user has logged in via wp-login.php at least once before. If not it will returns a 403 error until you user wp-login.php to log in.

Looks like the plugin adds the user to Wordpress database when it log in via wp-login.php but not via REST.

I would like to avoid a CRON job importing users to Wordpress. Is there any way to validate the user with Active Directory using the 'rest_authentication_errors' wordpress filter (or similar for REST)?

The plugin is running in Wordpress 5.0.3 and using JWT Authentication for the WP REST API plugin

**Comment by schakko** [comment]
I've just taken a quick look into the latest trunk version of the plug-in. So far from the code (https://plugins.svn.wordpress.org/jwt-authentication-for-wp-rest-api/trunk/public/class-jwt-auth-public.php), NADI should be triggered, even with a JWT authentication. JAWPREST only delegates to wp_authenticate(), in which we hook into.
Are you seeing any errors in NADI's debug.log when logging in with a JWT?

**Comment by xBau** [comment]
Inside logs folder there is only one file named "nadi-debug.log" but it has 0 bytes. It's empty.
I checked the log file after receiving the error being the "enable logging" checkbox enabled.

I forgot to mention that the error is a cors error. This is the response I get when I try to log in without logging in via wp-login.php before.

body: (...)
bodyUsed: true
headers: Headers {}
ok: false
redirected: false
status: 403
statusText: "Forbidden"
type: "cors"
url: "mydomain.com/wp-json/jwt-auth/v1/token"

**Comment by schakko** [comment]
@xBau I am closing this as this seems not being something related to NADI. The CORS error does not come from NADI but either from WP or more likely from the JWT plug-in. Check your JWT_AUTH_CORS_ENABLE setting (https://de.wordpress.org/plugins/jwt-authentication-for-wp-rest-api/).
If you can further investigate this issue and show which part of NADI does fail or want us to investigate this issue on a paid base, let me know.

**Comment by xBau** [comment]
Thanks @schakko , you helped me pointing to JWT plugin anyway. I will investigate it.

**Comment by xBau** [comment]
I've moved all the fetch part to the Main process on Electron to avoid the CORS issue, but login in via JWT without login in at wp-login.php first returns this 403 error.

```
{
  "code": "[jwt_auth] invalid_username",
  "message": "<strong>ERROR<\/strong>: Invalid username. <a href=\"https:\/\/iberialinks.partner.fjordnet.com\/wp-login.php?action=lostpassword\">Lost your password?<\/a>",
  "data": {
    "status": 403
  }
}
```

Summarizing the steps to reproduce the issue:
1.- AD user tries to login in the app (JWT auth) and it will fails. **403 error, invalid username.**
2.- Same user login via wp-login.php. **It works like a charm.**
3.- Same user tries to login via the app (JWT auth) again. **It works like a charm.**

**Comment by xBau** [comment]
I just made a pr that should solve this. https://github.com/NeosIT/active-directory-integration2/pull/121
