### ISSUE TITLE
SSO No profile found for authentication

### ISSUE THREAD

**Issue by aquastern** [NeosIT/active-directory-integration2#102]
Hello, i get the error

"2019-02-20 08:45:43 [ERROR] NextADInt_Adi_Authentication_SingleSignOn_Service::authenticate [line 146] User could not be authenticated using SSO. No profile found for authentication.
"

I think the SSO don't give the Suffix @xy.de with.

My REMOTE_USER give only my username without @xy.de because my Profiles on Wordpress is only the username.
When i deactivate KrbLocalUserMapping On in Apache i get this error:

Local WordPress user '[user@xy.de](mailto:user@xy.de)' could not be found

because Wordpress user is only username. How can i solve this? Please help

**Comment by schakko** [comment]
Has your default profile any account suffix defined?

**Comment by jbostoen** [comment]
Are you using Apache? Turns out it's the KrbLocalUserMapping which needs to be "Off" (so the full name is given, including domain)
