### ISSUE TITLE
Cannot create user because of duplicate email address

### ISSUE THREAD

**Issue by pokertour** [NeosIT/active-directory-integration2#103]
Hello,

i have a problem with user creation with the same email address, i've configured the plugin to allow the duplicate email : 
![image](https://user-images.githubusercontent.com/7757451/53418015-17b4fd80-39d7-11e9-9fd4-97444a3913d1.png)

But it seem when i want a third user with the same email than two others i can't, see the log : 
![image](https://user-images.githubusercontent.com/7757451/53417975-066bf100-39d7-11e9-9abd-5b556bcc551f.png)

Are you aware of this issue ?

Thx ;)

**Comment by schakko** [comment]
My guess is this is no longer allowed with WordPress >= 5.x.

**Comment by pokertour** [comment]
hum ok, do you have any solutions ?

**Comment by schakko** [comment]
After having this issue opened for more than two years, there is unfortunately no practical solution. For 2.4 we will remove this feature.
