### ISSUE TITLE
Email address conflict handling bug

### ISSUE THREAD

**Issue by roryashfordbentley** [NeosIT/active-directory-integration2#107]
Hey Neos team!

Thanks for your previous help with integration, everything is just about perfect except for one possible issue.

In the AD we are syncing into WP the majority of users don't have a unique email address, they use something like `genericemail@domain.com`.

I noticed within the configuration settings that there is a setting called Email address conflict handling. So I tried setting this to `Create` saving and running a new Sync. this did not work and the users with duplicate email addresses were not imported.

I did some digging and found the code that processes this on `line 612` of `classes/adi/user/Manager.php`.

```
if (NextADInt_Adi_User_DuplicateEmailPrevention::CREATE == $duplicateEmailPrevention && !$userData->user_email)
```

The above code checks for the `Create` value but then also checks for an _empty_ email address which prevents the user from being created when they have a duplicate email address because their email is not empty.

I have simply fixed this by replacing the line with the following.

```
if (NextADInt_Adi_User_DuplicateEmailPrevention::CREATE == $duplicateEmailPrevention  && $userData->user_email) {
```

I wanted to get your feedback to see if Im right but if you agree I'm happy to submit a PR. :)

**Comment by schakko** [comment]
Hi Rory,
thank you for this issue. I've added it to our internal bugtracker (ADI-691). Unfortunately we cannot easily change this logic. Instead, with one of the next versions (not sure if it will fit into 2.1.9) we'll add a new hook which you then can use.

**Comment by schakko** [comment]
@roryashfordbentley I've already updated the documentation (http://active-directory-wp.com/docs/API/User.html), you can use the filter next_ad_int_user_create_email for your purposes.
