### ISSUE TITLE
program time out before syncing all users

### ISSUE THREAD

**Issue by Geosimp** [NeosIT/active-directory-integration2#108]
I am unable to get all the users to sync without the program timing out. I can only sync two users per run.

**Comment by roryashfordbentley** [comment]
We were able to solve a very similar issue of syncing 200+ users by switching over to the WP-CLI method of the sync command explained here: https://active-directory-wp.com/docs/Premium_extensions/WP-CLI.html

**Comment by schakko** [comment]
@Geosimp As @roryashfordbentley has mentioned, the WP-CLI extension is developed for circumventing proxy timeouts.
