### ISSUE TITLE
Disabled parameter in Active Directory

### ISSUE THREAD

**Issue by heatleyyy** [NeosIT/active-directory-integration2#110]
Hi guys! We have one problem with Active Directory integration to Wordpress.
When our user in AD Disabled - NADI in synch logs wrote - Skipping import, because user Deactivated in AD. Thats Right! But...
In WordPress profile this user dont -DISABLED in his E-mail. I need help, wich parameter in AD i will delete, for NADI changing user email to DISABLED.

Thanks a lot!!!

**Comment by schakko** [comment]
Should be fixed with the latest release.
