### ISSUE TITLE
not synchronize all users

### ISSUE THREAD

**Issue by DarkRyo** [NeosIT/active-directory-integration2#111]
I have my AD with several OUs, I have used the top level DN in the plugin's setup but 
only synchronizes with users in the "Users" folder (screenshot of my tree) 
![image](https://user-images.githubusercontent.com/9272466/60603837-7d016c80-9d84-11e9-8d37-964007fb744b.png)

I have tried different ways to set the base DN but I did not achieve anything, so I turn to this group if someone has an idea of ​​what may be wrong

Sry for the bad grammar

EDIT: also the top lvl DN rightnow is this: DC=abc,DC=com,DC=yp

**Comment by schakko** [comment]
- Wrong DN for your search path? Please note that you have to use OU=... and not CN=... for your masked sub-directories (http://www.selfadsi.org/ldap-path.htm)
- Some special characters inside the DN names?

**Comment by DarkRyo** [comment]
Hi! what a time to be alive boiz. i get the solution along time ago but never come to see this post again, so there is:
I just use the DN like this 

`DC=tlp,DC=com,DC=py`

and finally in the enviroment settings i just use the **port 3268** in my case, then the sync correctly. 
this is a _intranet_ so i dont now really how works that port in terms of security... actually i dont remember why i get that port, just i search a lot in google xD..

again sry for my bad grammar 
regards
