### ISSUE TITLE
Sync to Wordpress: email address change not being applied

### ISSUE THREAD

**Issue by smfatwork** [NeosIT/active-directory-integration2#112]
When we have users who get married and change their last name, the user's Active Directory entry is updated - both their sAMAccountName and mail to reflect the name change.  The sync to wordpress handles updating their name, but doesn't update their login or email address in wordpress.

For the email address, I've been able to trace through the sync process to NextADInt_Adi_User_Manager::updateEmail and see that the comparison between the new email and what I think should be the current email address of their matching wordpress user isn't recognizing they are different (lines 571-574).  I traced into NextADInt_Adi_User_Manager::handleEmailAddressOfUser and the initial check to see if the new email exists (preferredEmail) ends up returning the new/preferred email (lines 594-597) causing the comparison used to see if the new is different from the current to fail (meaning they aren't different) because its comparing the new email to the new email instead of the new email to the old/current email on the wordpress user (ie $wpUser->get('user_email')).

If the email passed into NextADInt_Adi_User_Manager::updateEmail is supposed to be the current wordpress email address, it isn't because in NextADInt_Adi_User_Manager::update its pulling the email address from the ldapAttributes (which is the new address in AD).

I think I can work around this issue by implementing the after synchronize hook and doing the updates there.

**Comment by tylerkowalchuk** [comment]
I ran into this same issue... It's actually WordPress that doesn't allow usernames to be changed. They prefer you create a new account and disable the old one. None of the built-in WordPress functions allow editing the username so you have to edit the tables manually. I'm sure this can and probably will cause problems with other features/plugins that store the username instead of ID, but I went ahead and implemented this anyways because I have 1000+ users and less than 10 that contribute content. I will address those issues when one of those 10 people need to change their name ;)

Use at your own risk.
```
// fix sync of users when username changes
add_filter('next_ad_int_ad2wp_after_user_synchronize', 'updateUserLogin', 10, 4);

function updateUserLogin($syncStatus, $adiUser, $credentials, $ldapAttributes){
	global $wpdb;

	try{
	        $user_id = $adiUser->getId();
		$old_user_login = strtolower($adiUser->getUserLogin());
		$new_user_login = strtolower($ldapAttributes->getFilteredValue('samaccountname'));
		$new_user_email = strtolower($ldapAttributes->getFilteredValue('mail'));

		// check if username changed
		if($old_user_login !== $new_user_login){
                	// update users table
			$user_update = $wpdb->update($wpdb->users, array('user_login' => $new_user_login, 'user_nicename' => $new_user_login, 'user_email' => $new_user_email), array('ID' => $user_id));
			// update meta table
			$meta_update = $wpdb->update($wpdb->usermeta, array('meta_value' => $new_user_login), array('user_id' => $user_id, 'meta_key' => 'nickname'));
		}
	}catch(\Exception $e){
		
        }
}
```

**Comment by schakko** [comment]
Thank you for your reply @tylerkowalchuk. Because of possible compat issues we don't want to do anything here :-/
