### ISSUE TITLE
Cant install plugin

### ISSUE THREAD

**Issue by ryanschader** [NeosIT/active-directory-integration2#113]
Upgrading out ADI plugin to Next ADI in order to enable LDAPS which wasnt working on ADI.

When trying to activate the plugin I am getting fatal errors. "Plugin could not be activated because it triggered a fatal error."

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in C:\inetpub\wwwroot\WordPressSites\learning\wp-includes\meta.php on line 952

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in C:\inetpub\wwwroot\WordPressSites\learning\wp-includes\plugin.php on line 459

**Comment by schakko** [comment]
@ryanschader It seems that your PHP maximum memory limit is set to 32MB. Please try to upscale it to something like 128M, see https://premium.wpmudev.org/blog/increase-memory-limit/
