### ISSUE TITLE
Wordpress 5.2.3 - no Settings in admin dashboard?

### ISSUE THREAD

**Issue by Destabilizator** [NeosIT/active-directory-integration2#114]
I can't find a way to open settings, NADI is not in dashboard menu nor is "Settings" under plugin name in Plugins. Plugin works though

**Comment by gansad** [comment]
I just installed the plugin today, and having the same issue --- this cannot be a bug. How did you solve yours @Destabilizator  ?

**Comment by Destabilizator** [comment]
@gansad beats me, I have plugin 2.1.10 and WP WordPress 5.3.2 and it shows
