### ISSUE TITLE
Add custom metadata to user on first login

### ISSUE THREAD

**Issue by markbattistella** [NeosIT/active-directory-integration2#115]
Hi, is there a way to add custom metadata to a user when they first log in? Or a way to link them to a role as I use the role they are assigned to as a way to check which page they can view as I have a mix of LDAP and local users.

**Comment by schakko** [comment]
A special hook for the first log in is not present in NADI and I am not aware of any hooks for this in WordPress directly. But you can set a meta field with the number of logins; if this has not been set, it's the first login of the user.
That being said, you can use NADI's next_ad_int_auth_after_create_or_update_user filter (http://active-directory-wp.com/docs/API/Authentication.html) to update meta fields after the login or hook into WordPres' authenticate filter.
