### ISSUE TITLE
Next Active Directory Integration - Azure - Network Activate |

### ISSUE THREAD

**Issue by MCwpuser** [NeosIT/active-directory-integration2#116]
Next Active Directory Integration - Azure - Network Activate

Migrating our website from on-prem to Azure cloud.

How would you go about to Activate Network Activate for the Next Active Directory Integration plug-in.  

Error:
The 'Next Active Directory Integration' plugin requires the PHP module 'ldap' for communicating with the AD server. Please enable it.
For further information please visit https://secure.php.net/ldap.

How would I get to set up the plug-in in Azure

Thanks for any help!

**Comment by schakko** [comment]
Please install php_ldap on the given server, see http://active-directory-wp.com/docs/Installation.html

**Comment by MCwpuser** [comment]
WIll look into this, we're running WordPress as an App Service so I don't have access to the server.

**Comment by MCwpuser** [comment]
Thanks for the reply,   Were running WordPress as a Linux app service.  I will get in contact with Microsoft.
