### ISSUE TITLE
User Creation

### ISSUE THREAD

**Issue by seththesudoguy** [NeosIT/active-directory-integration2#117]
When flipping through the documentation I see that wordpress to active directory user creation is not supported yet?

**Comment by schakko** [comment]
Exactly. There are too much corner cases to provide this feature.

**Comment by seththesudoguy** [comment]
How do you mean? This would be an awesome feature

**Comment by schakko** [comment]
It would be indeed an awesome feature but the effort for implementing a working solution for most of the users would be too high. If you like to provide a PR or sponsor this feature, let us know.
