### ISSUE TITLE
WP 5.3 / NADI 2.1.9 / Sync2Wordpress DB Error 

### ISSUE THREAD

**Issue by gorti** [NeosIT/active-directory-integration2#118]
After update both WP and Plugin got this errormessage... any suggestion to solve the problem is?

WordPress-Datenbank-Fehler: [Duplicate entry '2-0' for key 'PRIMARY']
INSERT INTO `wp_wysija_user_list` (`user_id`, `list_id`, `sub_date`) VALUES (0, 2, 1574668672)

**Comment by schakko** [comment]
wp_wysija seems to come from an old Mailpoet version. We don't support this plug-in and are not aware of any official integrations. Because of this, I'll have to close this issue.

**Comment by gorti** [comment]
Ok, thanks anyway! Update to Mailpoet 3 solved the problem...
