### ISSUE TITLE
Username/Password being saved in Database

### ISSUE THREAD

**Issue by troytempleman** [NeosIT/active-directory-integration2#123]
Hi, 

After activating and setting up the plugin, I notice any users who login to the site will be displayed on the Users page after they login the first time. I can also see these users in the database, along with an encrypted password. 

Is it possible to not save the users in WordPress or database? If so, how?

Thanks!

**Comment by schakko** [comment]
WordPress requires that a password (= any password) is stored in the WordPress database. If you don't have *Set local password on first successful login* enabled (https://active-directory-wp.com/docs/Configuration/Password.html), there should not be any security problems.
