### ISSUE TITLE
In multisite "Blog admin sets the option value" has no effect

### ISSUE THREAD

**Issue by empereira** [NeosIT/active-directory-integration2#124]
Hello,

I created a new profile and configured all the entries for our AD. In the profile assignment I marked the two sites we have and selected my profile. When accessing the website panel and checking the profile settings, some things are not saved.

How to proceed?

**Comment by schakko** [comment]
Please specify your question. From your post I can't derive what does not work.

**Comment by empereira** [comment]
Ok.

Via network panel I configured the profile. For example, this option:
![image](https://user-images.githubusercontent.com/29874574/77861293-650f2a00-71ea-11ea-8651-c0819ec53def.png)

When I go to the panel of a "site" that is configured with the profile, nothing appears and at first I need to configure it manually, correct?
![image](https://user-images.githubusercontent.com/29874574/77861325-9687f580-71ea-11ea-8cfa-a4cf65a7152c.png)

**Comment by tmu-sprd** [comment]
Having the same problem, specifying it a bit more.

If an option has the permission "Blog admin sets the option value.", the sites using the profile do not use the value set in the profile options. They are only used, if any other permission is set, but then the option can't be changed at the site.

The [documentation](https://active-directory-wp.com/docs/Configuration/Multisite_configuration/Profile_options.html) states: "If the blog administrator does not change the value, the value of the assigned profile is used."
That's not the case at my installation.

Versions:
WordPress 5.3.2 Multi-Site
NADI 2.1.11
