### ISSUE TITLE
Nadi and Kerberos for machine out of domain

### ISSUE THREAD

**Issue by snopims** [NeosIT/active-directory-integration2#125]
Hello,
I am using Next Active Directory Integration with Kerberos for SSO. 
When my user is on the domain AD, SSO works.
When my user is out of session domain AD (or private mode), the user gets a prompt on the browser, it's not user friendly. I want to display the WP authentication page by default (link AD authentification), this is possible in this case.
Best regards

**Comment by schakko** [comment]
@snopims This is not a question related to NADI but how Kerberos/your webserver is configured. Please read https://active-directory-wp.com/docs/Networking/Single_Sign_On/Accessing_WordPress_without_a_valid_SSO_user.html for more information.

Greetings,
Schakko

**Comment by snopims** [comment]
Hi 

Thanks for your reply.
Kerberos is in front of WP/Nadi.

Indeed the only solution seems to be
"
It is also possible to create a second virtual host which has Kerberos not activated. You are ending up with having two virtual hosts like https://sso.test.ad (with Kerberos) and https://no-sso.test.ad (without Kerberos).
"
It is not easy for a small business.

Greetings
