### ISSUE TITLE
Can't Authenticate

### ISSUE THREAD

**Issue by Cheeky917** [NeosIT/active-directory-integration2#128]
Hello Everyone, i've configured and all tests works fine. But the authentication itself on wp-login.php doesn't work...

I'm using Wordpress 5.5.1 on ubuntu 20.04 and Apache2 last version.

I've configured the AD connection with LDAPS and put the certificate on my server. When i test the authentication I have this warning : 
WARNING | Username for the sync user does not  contain a correct suffix. If the connection to the ad fails, this could  be the cause. Please make sure you have added all UPN suffixes to the  configuration tab User -> Account suffix.

And I see that the suffix that i've setup is not used : 

DEBUG | account_suffix =

But it's retreived later in the connection process.

Well i've spend all my morning trying to solve this problem.

Please I need help.

Best regards

**Comment by schakko** [comment]
There is a misconfiguration of NADI. Please read the documentation carefully or purchase a support plan and professional support.
