### ISSUE TITLE
Error wp-login with NTLM SSO

### ISSUE THREAD

**Issue by Munnday** [NeosIT/active-directory-integration2#13]
Running IIS under Windows Server 2012r2

When enabling SSO, attempting to connect via SSO results in an HTTP 500 Error

> PHP Logs:
> [09-Sep-2016 04:25:50 UTC] PHP Fatal error:
> Uncaught TypeError: Argument 1 passed to NextADInt_Adi_Authentication_Ui_ShowBlockedMessage::__construct() must be an instance of NextADInt_Multisite_Configuration_Service,
>     none given, called in wp-content\plugins\next-active-directory-integration\classes\Adi\Dependencies.php on line 1102 and defined in 
> 
> \wp-content\plugins\next-active-directory-integration\classes\Adi\Authentication\Ui\ShowBlockedMessage.php:33

**Comment by Tobi823** [comment]
Hi Munnday,

i could reproduce and the fix the bug. Can you verify that the fix works for you? https://downloads.wordpress.org/plugin/next-active-directory-integration.zip

**Comment by Tobi823** [comment]
I will upload the fixed version during the next hour.

@Munnday I want to add your name to the changelog on wordpress.org. Is that ok for you?

**Comment by Munnday** [comment]
@Tobi823 - no issue using my name :).

Still can't seem to get things working as intended here though - the fix does fix the error that was occurring - however on  the wp-login page, clicking sso login link just appears to add ?reauth=sso to the url, but nothing happens.

I believe the settings on he SSO page of the plugin are correct - the account being used for the sso lookup has permission in ActiveDirectory

**Comment by ReneLuecking** [comment]
Maybe you have the same problem like me: neither "$_SERVER['REMOTE-USER']" nor "$_SERVER['X-REMOTE-USER']" are existing so SSO cannot work because of the missing user name.

Look in the debug.log of the plugin (logs/debug.log). Do you see the sentence "Cannot find username for SSO."?

**Comment by Munnday** [comment]
> •does the test tool work (admin.php?page=next_ad_int_test_connection) ?
Yes, authenticates without issue - creates the user account (tested after this with the user account created and still couldn't connect with sso - same error in debug.log

> •is  Use sAMAccountName for newly created users  enabled?
Yes. turning off sso and logging in creates the user account as expected with the plugin

> •is  Enable SSO  enabled?
Confirmed :)

**Comment by Tobi823** [comment]
Can you add this to the index.php?

echo "<pre>";
var_dump($_SERVER);
echo "</pre>";

You should see something like this:
  ["REMOTE_USER"]=>
  string(21) "Administrator@TEST.AD"

or that:
  ["X_REMOTE_USER"]=>
  string(21) "Administrator@TEST.AD"

If $_SERVER does not contain REMOTE_USER or X_REMOTE_USER then:
- `Service account username` is wrong
- `Service account password` is wrong
- your webbrowser dont trust Kerberos (https://ping.force.com/Support/PingFederate/Integrations/How-to-configure-supported-browsers-for-Kerberos-NTLM)
- your Kerberos is not correct configured
- you access the webserver via IP address (please use the DNS name like http://webserver.test.ad/wordpress)
- the time between AD and webserver is not equal

See https://www.active-directory-wp.com/docs/Networking/Single_Sign_On/index.html for more details

**Comment by Munnday** [comment]
'REMOTE_USER' => string 'domain\\username' (length=17)

IIS doesn't seem to pass though the username as user@domain.local - which looks to be the issue

**Comment by schakko** [comment]
Hi @Munnday!
As stated in https://www.active-directory-wp.com/docs/Networking/Single_Sign_On/index.html we do not support the Down Level logon-name (https://msdn.microsoft.com/de-de/library/windows/desktop/aa380525(v=vs.85).aspx). The NetBIOS domain name must not inevitably correlate to your actual domain's DNS entr. Meaning, that your domain DNS suffix could be *test.ad* but your NetBIOS domain name is *mydomain*. At the moment the plug-in has only support for the user principal name (@domain).

Please take a look at http://www.techpaste.com/2016/02/remote-user-header-variable-in-iis/ and follow the instructions changing the format of REMOTE_USER from domain\username to username@domain.

**Comment by Munnday** [comment]
@schakko - makes total sense.  Can confirm that the work around appears to be working as intended (although isn't ideal :))

Thanks!

**Comment by Tobi823** [comment]
@edomelters @Munnday 
Thanks to tmuikku (https://wordpress.org/support/topic/fatal-error-after-login-and-suffix-question/) I have discovered a simple solution for supporting Down-Level Logon Name (also known as pre-Windows 2000 user logon name like domain\username). 

We still don't recommend to  enable the "Allow Down-Level Logon Name for login" feature because this logon name is not unique and can cause problems in some corner cases. But I should work for the majority of the Active Directories.

You can find this option in version 2.0.5 under the "User" tab.

**Comment by edomelters** [comment]
Hi @Tobi823 thanks for adding this option to the plugin. I enabled the feature under the user tab but when browsing to our local wordpress instance i still don't get a automatic sign in. Also when navigating to 'log in' and use the 'log in with sso' nothing happens except the url changes. 

I have checked our server settings with a php test file and my remote user setting is this;
["REMOTE_USER"]=> string(12) "VOGELS\emelt

I can login with both VOGELS\emelt as emelt only though using my AD credentials.

The only thing missing is automatically signing in...

**Comment by Tobi823** [comment]
@edomelters Can you add `var_dump($password); die();` to vendor/adLDAP/adLDAP.php line 485?

I think this bug is related to https://github.com/NeosIT/active-directory-integration2/issues/20 and is caused by the WordPress behavior of escaping every element in $_POST, $_GET, $_SERVER etc.

https://github.com/WordPress/WordPress/blob/master/wp-includes/load.php#L653

**Comment by edomelters** [comment]
Hi @Tobi823 thanks for getting back to me so quickly. I have added the line you mentioned but not much is happening. 

When browsing to our wordpress no login happens. When going to the login screen nothing happens. When clicking on the 'log in with sso' hyperlink the following action occurs in my console but everything keeps blank and nothing really happens.

Navigated to http://vogelsh18/wp-login.php?redirect_to=http%3A%2F%2Fvogelsh18%2F&reauth=sso

**Comment by Tobi823** [comment]
Hi @edomelters 

does version 2.0.6 work for you?

**Comment by edomelters** [comment]
Hi @Tobi823 sorry for the late reply. I have installed the latest version 2.0.9 but no progress on the automatic sign in.. Is it possible that you or someone else can assist us by teamviewer?

**Comment by schakko** [comment]
@edomelters If you need professional support, please visit our service page on https://www.active-directory-wp.com/service-for-active-directory-and-wordpress/.

**Comment by edomelters** [comment]
@schakko i have left you guys a message a week ago but i have no response.. Would like your support

**Comment by Munnday** [comment]
I'd just like to add, that I am experiencing the same situation as @edomelters when attempting to use the plugin with the down level option

**Comment by laughtonsm** [comment]
@Munnday would be interested to hear how you got Helicon working for you.  Thus far, the ISAPI filter loads, but no re-writing is occurring

**Comment by FatSquirrel93** [comment]
Closed due to no more responses/questions.
