### ISSUE TITLE
How to log User’s Last Login Date when using SSO

### ISSUE THREAD

**Issue by tibetoine** [NeosIT/active-directory-integration2#130]
Hello, I'm using SSO (through Kerberos),

I would like a way to record User’s Last Login Date.

I tried this : 
```
function user_last_login( $user_login, $user ) {
    update_user_meta( $user->ID, 'last_login', time() );
}
add_action( 'wp_login', 'user_last_login', 10, 2 );
```

But this only work for user who log in through login form (not SSO)

**Comment by schakko** [comment]
You can use the [next_ad_int_auth_after_create_or_update_user hook](https://active-directory-wp.com/docs/API/Authentication.html) for this.
