### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Ahmis** [NeosIT/active-directory-integration2#132]
WordPress 5.7
Next Active Directory Integration 2.1.12

Gives the following error:

Tiedoston /var/www/project/web/app/plugins/next-active-directory-integration/classes/Adi/Synchronization/WordPress.php rivillä 343 havaittiin virhe lajia E_ERROR. Virheviesti: Uncaught TypeError: Unsupported operand types: string & int in /var/www/project/web/app/plugins/next-active-directory-integration/classes/Adi/Synchronization/WordPress.php:343 Stack trace: #0 /var/www/project/web/app/plugins/next-active-directory-integration/classes/Adi/Synchronization/WordPress.php(408): NextADInt_Adi_Synchronization_WordPress->isAccountDisabled('') #1 /var/www/project/web/app/plugins/next-active-directory-integration/classes/Adi/Synchronization/WordPress.php(133): NextADInt_Adi_Synchronization_WordPress->synchronizeUser(Object(NextADInt_Adi_Authentication_Credentials), '4a13321f-6bdd-4...') #2 /var/www/project/web/app/plugins/next-active-directory-integration/classes/Adi/Cron/UrlTrigger.php(170): NextADInt_Adi_Synchronization_WordPress->synchronize() #3 /var/www/project/web/app/plugins/next-active-directory-integration/classes/Adi/Cron/UrlTrigger.php(98): NextADInt_Adi_Cron_UrlTrigger->dispatchAction(false, 1) #4 /var/www/project/web/app/plugins/next-active-directory-integration/classes/Adi/Cron/UrlTrigger.php(67): NextADInt_Adi_Cron_UrlTrigger->processHttpRequest(Array) #5 /var/www/project/web/wp/wp-includes/class-wp-hook.php(292): NextADInt_Adi_Cron_UrlTrigger->httpRequestEntryPoint('') #6 /var/www/project/web/wp/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #7 /var/www/project/web/wp/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #8 /var/www/project/web/wp/wp-settings.php(560): do_action('init') #9 /var/www/project/web/wp-config.php(15): require_once('/var/www/projec...') #10 /var/www/project/web/wp/wp-load.php(42): require_once('/var/www/projec...') #11 /var/www/project/web/wp/wp-admin/admin.php(34): require_once('/var/www/projec...') #12 {main} thrown

**Comment by schakko** [comment]
@Ahmis Can you let me know which version of PHP are you using? Already 8.x?

**Comment by Ahmis** [comment]
Thanks for the quick reply! Yes, we are using PHP 8.

**Comment by schakko** [comment]
We'll fix this with the upcoming 2.2.0 version. Until then, you can fix it by changing https://github.com/NeosIT/active-directory-integration2/blob/ebc85bb5d92d30da3d355763e00bc28b568a3fa6/classes/Adi/Synchronization/WordPress.php#L277 into 
```
return (int)$uac;
```

For reference, we got hit by https://wiki.php.net/rfc/arithmetic_operator_type_checks.

**Comment by Ahmis** [comment]
Good to hear, thank you!
