### ISSUE TITLE
Deprecated: Required parameter follows optional parameter

### ISSUE THREAD

**Issue by gigiogigi1** [NeosIT/active-directory-integration2#137]
Hi, I get these three error messages (PHP 8.0, WP 5.7) on the login page:

Deprecated: Required parameter $mode follows optional parameter $args in [...]\wp-content\plugins\next-active-directory-integration\classes\Core\Persistence\WordPressRepository.php on line 113

Deprecated: Required parameter $ldapData follows optional parameter $attributeNames in [...]\wp-content\plugins\next-active-directory-integration\classes\Ldap\Attribute\Service.php on line 58

Deprecated: Required parameter $wpUser follows optional parameter $useLocalWordPressUser in [...]\wp-content\plugins\next-active-directory-integration\classes\Adi\Mail\Notification.php on line 79

**Comment by schakko** [comment]
Thank you for letting us know! It will be fixed with the upcoming 2.3.0 version.
