### ISSUE TITLE
Unable to disable Brute-Force Protection

### ISSUE THREAD

**Issue by Munnday** [NeosIT/active-directory-integration2#14]
When setting the Brute-Force Protection setting to '0' to disable, the screen saves - howevere navigating away from the NADI screens back back to the Security Page, the setting resets to the default value of '3'

When attempting to leave the field blank (it states you can leave it as blank or '0' the error displays

> Maximum login attempts has to be numeric and cannot be negative

**Comment by Tobi823** [comment]
I have fix the bug. Can you verify it?

**Comment by Tobi823** [comment]
The bug is fixed. If the bug still exists, please drop us a line.
