### ISSUE TITLE
SSO with Basic Auth broken since 2.2.0

### ISSUE THREAD

**Issue by alxndrbauer** [NeosIT/active-directory-integration2#142]
We are using an extra basic auth when we´re connecting to our wordpress site from outside our network.
After preauthentication via basic auth we were redirected to the wordpress login page.

Since 2.2.0 its not working anymore. Instead of the loginform, we are now presented an error message: Critical error occured on your website.

These are the error messages from the logs:

`
PHP Fatal error:  Uncaught Error: Call to a member function getProfile() on null in /releases/20210528130411/web/app/plugins/next-active-directory-integration/classes/Adi/Authentication/SingleSignOn/Service.php:165\nStack trace:\n#0 /releases/20210528130411/web/app/plugins/next-active-directory-integration/classes/Adi/Authentication/SingleSignOn/Service.php(125): NextADInt_Adi_Authentication_SingleSignOn_Service->delegateAuth()\n#1 /releases/20210528130411/web/wp/wp-includes/class-wp-hook.php(292): NextADInt_Adi_Authentication_SingleSignOn_Service->authenticate()\n#2 /releases/20210528130411/web/wp/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()\n#3 /releases/20210528130411/web/wp/wp-includes/plugin.php(484): WP_Hook->do_action()\n#4 /releases/20210528130411/web/wp/wp-settings.php(560): do_action()\n#5 /releases/20210528130411/web/wp-config.php(9): require_once('/var/ww in /releases/20210528130411/web/app/plugins/next-active-directory-integration/classes/Adi/Authentication/SingleSignOn/Service.php on line 165
`

```
2021-05-28 16:13:29 [DEBUG] NextADInt_Adi_Authentication_SingleSignOn_Service::findUsername [line 222] SSO provided username for environment variable "REMOTE_USER" is "BASIC_AUTH_USER'
2021-05-28 16:13:29 [DEBUG] NextADInt_Adi_Authentication_SingleSignOn_Profile_Locator::locateBySuffix [line 92] Looking up SSO profile by UPN suffix fallback for credential 'Credentials={login='basic_auth_user',sAMAccountName='basic_auth_user',userPrincipalName='basic_auth_user',netbios='',objectGuid='',wordPressUserId='',kerberosRealm=''}'
2021-05-28 16:13:29 [DEBUG] NextADInt_Adi_Authentication_SingleSignOn_Profile_Locator::locate [line 63] Profile match:
```

We are using kerberos and with 2.1.11 it works as expected.

Tested with 2.2.3

Has anyone an idea?

**Comment by schakko** [comment]
You are mentioning the user of Kerberos: With 2.2.0 we have introduced the support of Kerberos realms (https://active-directory-wp.com/docs/Configuration/SSO.html). Check the "Kerberos realm mappings" documentation to avoid problems with mismatches between any UPN suffix of your AD and your Kerberos realm.

**Comment by schakko** [comment]
- [ ] Use `isUsernameExcludedFromAuthentication` inside `NextADInt_Adi_Authentication_SingleSignOn_Service`
- [ ] Introduce a new hook, which is called inside `isUsernameExcludedFromAuthentication`
- [ ] Update unit tests (has the exclusion been considered? Has the hook been executed)
- [ ] Update API documentation
