### ISSUE TITLE
how force use sAMaccountName if UserPrincipalName is empty ; or how use only SAMaccountName

### ISSUE THREAD

**Issue by GowaP** [NeosIT/active-directory-integration2#143]
Hello,
in my AD, the "administrator account" do not have a UPN. Among other things, to block AZURE synchronization.

how to configure NADI to use sAMaccountName when the UPN is empty.
or, how to force NADI to use only the sAMaccountName in my unique domain.

Thank you.

**Comment by schakko** [comment]
As stated in #144 we require the userPrincipalName. 
I'd like to suggest that you add another user with a valid userPrincipalName or configure Azure AD Connect to include or exclude the administrator based upon a given attribute user security group membership (https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sync-configure-filtering).

**Comment by GowaP** [comment]
FR: Je comprends que vous utilisez l'UPN, mais pour un SSO, le GUID devrait être suffisant.
Pour AZURE, la gestion par groupe de sécurité ne fonctionne qu'en mode "mise en oeuvre".

EN: I understand that you are using the UPN, but for an SSO, the GUID should be sufficient.
For AZURE, security group management only works in "implementation" mode.
