### ISSUE TITLE
Blank page when UserPrincipalName empty.

### ISSUE THREAD

**Issue by GowaP** [NeosIT/active-directory-integration2#144]
Hello,
Wordpress displays a blank page when UserPrincipalName is empty.

NADI seems to accept the connection, probably identifying the user via the sAMaccountName. But once the authentication form is validated, the displayed page remains blank.

The F5 displays the authentication form again.

**Comment by schakko** [comment]
Hi @GowaP, 
due to the recent integration of Active Directory domain forest support we require a valid userPrincipalName. Thus being said, we can't dig deeper into this bug :-/

**Comment by GowaP** [comment]
FR: Le SID me semblerait plus pertinent pour ne pas bloquer les intranets mono domain.
EN: The SID would seem more relevant to me so as not to block single domain intranets.

**Comment by schakko** [comment]
Internally, we are using the objectGUID for uniqueness. But for validating the authentication, the userPrincipalName is required.

**Comment by GowaP** [comment]
FR : comment revenir sur la version 2.0.11 ?
EN: How do I go back to version 2.0.11?
