### ISSUE TITLE
Unable to save configuration chages in NADI plugin Configuration Screen

### ISSUE THREAD

**Issue by murali-ascent** [NeosIT/active-directory-integration2#147]
Hi,

I am new to WP NADI plugin. Just installed on my new WP instance v5.8.
When i do changes to configuration of NADI and click on Save button, it is not getting saved.
If I navigate to any other page/menu option and return to NADI Configuration as admin, the changes made were fully lost.

One of the log reports show as below,

Log Level	Log Message
INFO	Support for: ###unlicensed###https://..........................###imsnew###
INFO	Support Hash: f191ee3a96151be19f9fe749bcc15a115e6d08400421c1958cf5016d214d32b8
INFO	System Information:
INFO	- PHP: "7.4.23"
INFO	- WordPress: "5.8"
INFO	- Active Directory Integration: "2.0"
INFO	- Operating System: "Linux .................................. 5.4.0-81-generic #91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021 x86_64"
INFO	- Web Server: "apache2handler"
INFO	- adLDAP: "3.3.2 EXTENDED (20200626)"
INFO	*** Establishing Active Directory connection ***
[STATUS]	Logon failed.

Can any one help me resolve this quickly?

Thanks in Advance.

**Comment by schakko** [comment]
No response, so I'll close the issue.
