### ISSUE TITLE
Option to automatically create a site on login

### ISSUE THREAD

**Issue by Tawmu** [NeosIT/active-directory-integration2#15]
Not so much an issue but it'd be a really nice feature if a site was created for the user on initial login, perhaps with the blog titled the name of the account to begin with.

Thoughts?

Also, do you accept PRs from outsiders? :)

**Comment by schakko** [comment]
Hi @Tawmu and thanks for the comment,
ADI is based upon the Unix philosopy "Write programs that do one thing and do it well.". Creating new WordPress sites in a Multisite environment seems like a reasonable idea but does not really fit into the Unix philosophy. Such a feature should be implemented as a plug-in on its own. If you are interested in getting build such a plug-in by us, feel free to contact me or one of our team members to get a quote.

To answer your second question: we are glad and happty about every community feedback we can get, so: Yes, we accept PRs - as far as they help to fulfil ADI's goals. We would not accept a PR for your requested feature in this issue ;-)
