### ISSUE TITLE
Uncaught TypeError when checking userAccountControl attribute

### ISSUE THREAD

**Issue by MrEMan** [NeosIT/active-directory-integration2#151]
WordPress 5.8 and 5.9
Next Active Directory Integration: 2.3 and 2.3.1
PHP 8.0 and 8.1

I've tried various versions and reinstalled PHP but cannot get it to work.

Signing in works but clicking [Sync to WordPress] causes this error. There has been a critical error on this website. Please check your site admin email inbox for instructions.

This looks similar to https://github.com/NeosIT/active-directory-integration2/issues/132

`[Fri Feb 04 09:27:03.454701 2022] [proxy_fcgi:error] [pid 553355] [client 172.16.1.86:62551] AH01071: Got error 'PHP message: PHP Fatal error:  
Uncaught TypeError: Unsupported operand types: string & int in /var/www/html/wp-content/plugins/next-active-directory-integration/classes/Adi/Synchronization/WordPress.php:350\n
Stack trace:\n
#0 /var/www/html/wp-content/plugins/next-active-directory-integration/classes/Adi/Synchronization/WordPress.php(415): NextADInt_Adi_Synchronization_WordPress->isAccountDisabled()\n
#1 /var/www/wp-content/plugins/next-active-directory-integration/classes/Adi/Synchronization/WordPress.php(134): NextADInt_Adi_Synchronization_WordPress->synchronizeUser()\n
#2 /var/www/wp-content/plugins/next-active-directory-integration/classes/Adi/Synchronization/Ui/SyncToWordPressPage.php(114): NextADInt_Adi_Synchronization_WordPress->synchronize()\n
#3 /var/www/wp-content/plugins/next-active-directory-integration/classes/Adi/Synchronization/Ui/SyncToWordPressPage.php(69): ...', referer: https://oursite.com/wp-admin/admin.php?page=next_ad_int_sync_to_wordpress`

Regards

**Comment by schakko** [comment]
@MrEMan Can you checkout [75a2089](https://github.com/NeosIT/active-directory-integration2/commit/75a20890567fef78b27f3223dc3a8cccff11b1e7) or the latest develop branch and see if it works now?

**Comment by MrEMan** [comment]
This is going to sound weird.

I noticed the script was failing at some users so I removed them. I kept removing users until the script succeeded. All users now added back.

Regards
