### ISSUE TITLE
Configuration page is disabled

### ISSUE THREAD

**Issue by oneguy9** [NeosIT/active-directory-integration2#158]
Hi there. 
I'm using the plugin in a closed environment.
For soome reason all configuration is disabled.
I get a .block-ui div floating above all the page and I cannot click or save anything.
Even if I hide it, the result is the same.
Is there a solution for this?

**Comment by schakko** [comment]
@oneguy9 Are there any issues in the Web Developer's console?

**Comment by schakko** [comment]
Might be fixed with 2.3.5 and #164
