### ISSUE TITLE
Fatal error within Twig dependency

### ISSUE THREAD

**Issue by DrizzlyOwl** [NeosIT/active-directory-integration2#159]
Hello,

After recently deploying the latest v2.3.2 of the plugin, we are seeing occasional PHP Fatal Errors in our error log.

```
PHP Fatal error:  Uncaught Error: Class 'Twig\\ExtensionSet' not found in 
/vendor/twig/twig/src/Environment.php:117

Stack trace:
/classes/Multisite/View/TwigContainer.php(126): Twig\\Environment->__construct()
/classes/Multisite/View/TwigContainer.php(109): NextADInt_Multisite_View_TwigContainer->register()
/classes/Multisite/View/Page/Abstract.php(58): NextADInt_Multisite_View_TwigContainer->getTwig()
/classes/Multisite/View/Pa[...] 

in /vendor/twig/twig/src/Environment.php on line 117
```

This is simply using the downloaded version from the WP Plugin library. Can you please advise if this is a known fault?

This was triggered when attempting to use the 'Test authentication' screen within WordPress admin

**Comment by schakko** [comment]
@DrizzlyOwl This is first time I am hearing about this issue. 
- Can you check, if the file `wp-content/plugins/next-active-directory-integration/vendor/twig/twig/src/ExtensionSet.php` exists in your filesystem?
- What PHP version do you use?
- Are there other plug-ins in your WordPress environment which are using Twig as a dependency?

**Comment by schakko** [comment]
No response since 4 weeks, so I assume the issue has been resolved.
