### ISSUE TITLE
Undefined offset 0 error while doing AD to Wordpress Import

### ISSUE THREAD

**Issue by petterannerwall** [NeosIT/active-directory-integration2#16]
Hello!

I get the error below for each of the users im importing for my AD to Wordpress. The users are created alright and everything seems to work accordingly, Is there any setting i could try to change to get rid of the message, it kinda clutters down the import screen. 

![image](https://cloud.githubusercontent.com/assets/5909669/18473526/c139bf08-79bd-11e6-99b7-f702c145c410.png)

Thanks in Advance

**Comment by Tobi823** [comment]
Hi petterannerwall,

i have no time to repoduce this bug yet. But i guess that you are using primary group ids (like "id:689"). That _should_ have worked. Can you try a security group name (like "users") instead?

I will examine this bug tomorrow.

**Comment by petterannerwall** [comment]
Hi, no hurry!

I seem to have located the issue myself, our security groups have dashes in the name. An example would be "AllEmpl-CompanyName" and it seems the method cannot handle dashes. 

The error goes away if i type a group like Domain Users instead. 

Just for clarity, the field im talking about is the "Import members of security groups" under the "Sync to Wordpress" Tab

**Comment by Tobi823** [comment]
Hi petterannerwall,

I have created the security group AllEmpl-CompanyName2 in my Active Directory and added two users. I  changed the "Import members of security groups" value to AllEmpl-CompanyName2 but "Sync to WordPress" still works. Can you send me your logs/debug.log via email at the@neos-it.de? 

![screenshot from 2016-09-14 10-37-39](https://cloud.githubusercontent.com/assets/10066140/18505672/a1a9770e-7a68-11e6-82a8-482ec6a33122.png)
![screenshot from 2016-09-14 10-38-01](https://cloud.githubusercontent.com/assets/10066140/18505677/a619c8ac-7a68-11e6-8ff5-905ea92a8778.png)
![screenshot from 2016-09-14 10-38-46](https://cloud.githubusercontent.com/assets/10066140/18505679/a8fdd572-7a68-11e6-9548-0fc7882e7ca5.png)
![screenshot from 2016-09-14 10-39-13](https://cloud.githubusercontent.com/assets/10066140/18505682/ab8bb818-7a68-11e6-945b-9071763c3714.png)
![screenshot from 2016-09-14 10-42-16](https://cloud.githubusercontent.com/assets/10066140/18505683/ae119990-7a68-11e6-939a-fbd6572dd59d.png)

**Comment by petterannerwall** [comment]
Looks right to me, just followed your steps above creating a new group and ran into the same problem again. 

Just sent you a email with the debug.log

**Comment by neos-it-user** [comment]
Hi petterannerwall,

I could not reproduce your bug yet. I have built a new plugin version with increase logging. You can install this developer version by:
- deactivate the current Next Active Directory Integration plugin
- removing the folder "next-active-directory-integration" from wp-content/plugins/
- extract <https://downloads.wordpress.org/plugin/next-active-directory-integration.issue16.zip> https://downloads.wordpress.org/plugin/next-active-directory-integration.issue16.zip inside in wp-content/plugins/
- activate the plugin with the version "REPLACE_BY_JENKINS_SCRIPT" ?
Make sure that you use a WordPress user who is not authenticated by the Next ADI plugin.


Can you install the developer version, execute "Sync to WordPress" and send me your debug.log?
Are you using more than one Active Directory?
Are the users synced correctly (although the warning is shown)?


You can reinstall the stable version by:
- deactivate the plugin with the version "REPLACE_BY_JENKINS_SCRIPT"
- removing the folder "next-active-directory-integration" from wp-content/plugins/
- extract https://downloads.wordpress.org/plugin/next-active-directory-integration.2.0.3.zip inside in wp-content/plugins/
- activate the plugin with the version "2.0.3"

Your sincerely
Tobias Hellmann

**Comment by petterannerwall** [comment]
Hello

![image](https://cloud.githubusercontent.com/assets/5909669/18549418/a995b9aa-7b4e-11e6-8607-b44cb8c988f4.png)

No, im only using one AD
Yes, the users seem to be successfully synced 

The problem seems to persist for me, i get the same error on a different row
![image](https://cloud.githubusercontent.com/assets/5909669/18549721/74cedbdc-7b50-11e6-884c-36ade88068e5.png)

Just sent you the latest debug.log

Just ask if there is anything more i can do, planning on using your plugin in production in mid october if all goes well :)

**Comment by Tobi823** [comment]
Hi petterannerwall,

The bad news:
I could not reproduce your bug. adLDAP::get_primary_group has still issues to find the primary group of your Active Directory users and I dont know why.

The good news:
I discovered that this information (memberof) is completely unnecessary and decrease only performance. 

By changing this line in classes/Ldap/Connection.php:589
$userInfo = $adLdap->user_info($member);
to this:
$userInfo = $adLdap->user_info($member, array('objectsid'));
I can work around this bug and increase performance.

I will update the plugin as soon as possible.

**Comment by Tobi823** [comment]
The plugin has been fixed and uploaded. Can you verify that your problem is now solved?

**Comment by petterannerwall** [comment]
I upgraded to version 2.0.5 and i can't see any errors anymore while doing the import!

**Comment by Tobi823** [comment]
It might be possible, that "Role equivalent groups" does not work correctly.
For example:
You associated "Domain Users" with the WordPress role "admin".
The user "alpha" has as Primary Group "Domain User".
During "Sync to WordPress" the plugin calls get_primary_group and gets an empty results (instead of "Domain Users". The plugins thinks that "alpha" is not a member of "Domain Users" and does not assign the "admin" role to "alpha".

If this is the case, you have to use security groups, which are not being used as a Primary Group. Or you can try to enter the Primary Group ID instead the group name (for "Domain Users" it would be "id:513").
