### ISSUE TITLE
NADI 2.3.6 login error on PHP 7.4.19 (parameter to be array, null given…)

### ISSUE THREAD

**Issue by Eugene-Chernetsky** [NeosIT/active-directory-integration2#171]
After last update it is impossible to login via NADI:

`Warning: ldap_search() expects parameter 9 to be array, null given in …/plugins/next-active-directory-integration/vendor/adLDAP/adLDAP.php on line 1685`

Wordpress 6.1.1
NADI 2.3.6
PHP 7.4.19

Rollback to v2.3.5 for now

Should I move to PHP 8.x or it could be fixed in upcoming updates?

**Comment by schakko** [comment]
@Eugene-Chernetsky I've just released 2.3.7 to make NADI still compatible with PHP 7.4. You should soon upgrade to 8.1 anyways ;-)

**Comment by Eugene-Chernetsky** [comment]
> @Eugene-Chernetsky I've just released 2.3.7 to make NADI still compatible with PHP 7.4. You should soon upgrade to 8.1 anyways ;-)

Schakko, thanks a lot for quick reply!
Version 2.3.7 solved all issues last week!

**Comment by schakko** [comment]
@Eugene-Chernetsky Thank you for the feedback!
