### ISSUE TITLE
Conflit with wp-rocket

### ISSUE THREAD

**Issue by olybop** [NeosIT/active-directory-integration2#172]
When your plugin is activated, it sets a fatal error to the WP-rocket plugin activation. If your plugin is deactivated, everything works.

**Comment by schakko** [comment]
This has been probably fixed with the next release 3.0.0 (#169). You can try the latest release candidate. Please note, that at least PHP 8.0 is required.

**Comment by olybop** [comment]
yes my WP is on PHP8. 
Thx for that.
