### ISSUE TITLE
Websites crash on update

### ISSUE THREAD

**Issue by jpurpleman** [NeosIT/active-directory-integration2#179]
Hello,

The timing and release of 3.x does not meet my timelines in higher education to update servers and install more recent versions of server software.

My students who have WordPress websites are now reporting their sites are crashing when they update to the latest version.  I understand why and this will be learning experience for them.

To safeguard sites, would you be able to build in a php version test and if it fails, don't allow the plugin to activate therefore not creating php fatal errors, crashing the site.

Thank you.

**Comment by schakko** [comment]
@jpurpleman Thank you for the suggestion! I've created a patch in https://github.com/NeosIT/active-directory-integration2/commit/7a4a9dbf4a92ba5f3e572fadd3c1b9aff5d88759 - can you check that one out?

**Comment by schakko** [comment]
Included in 3.0.3
