### ISSUE TITLE
Updated NADI today. Critical website error

### ISSUE THREAD

**Issue by CelticWolf63** [NeosIT/active-directory-integration2#180]
Manually disabling plugin by renaming folder in wp-content\plugins has been my only workaround to get site up. Let me know if I can get you any other info

**Comment by jpurpleman** [comment]
The new version needs PHP 8.x.  I had to backrev my install to version 2.3.8.

**Comment by schakko** [comment]
I am closing this issue. As @jpurpleman already stated, NADI requires PHP 8.x. We can no longer support PHP 7.x as it is EOL and therefore we ran into other dependency issues.

**Comment by CelticWolf63** [comment]
Thanks, I restored to an older version and am back up and running.
