### ISSUE TITLE
option "User > Automatic user creation" not to be found

### ISSUE THREAD

**Issue by UlliGT** [NeosIT/active-directory-integration2#193]
Hi all! In the documentation it is mentioned on multiple occasions that option "User > Automatic user creation" must be enabled. This option is not available in my installation of NADI under Menu > Active Directory Integration > Configuration > User.

Or do you mean Menu > Settings > General > Membership > Anyone can register?

![NADI](https://github.com/NeosIT/active-directory-integration2/assets/32921819/f0b14249-b918-41f2-82c5-95e07c0663c0)

**Comment by schakko** [comment]
Thanks for mentioning it. "Automatic user creation" is implicitly enabled. We have just removed the corresponding comments from the documentation!
