### ISSUE TITLE
 random error Authentication for user 'xxx' failed [AD: Can't contact LDAP server] [AD error code: -1]

### ISSUE THREAD

**Issue by podloucka** [NeosIT/active-directory-integration2#194]
Randomly one of several login attempts will fail
[ERROR] Dreitier\Ldap\Connection::authenticateUser [line 394] Authentication for user 'xxx' failed [AD: Can't contact LDAP server] [AD error code: -1]
sometimes I log in only on the third or fifth attempt
sometimes I log in for the first time
where could be the problem
Thank you

**Comment by schakko** [comment]
@podloucka error code -1 means that your AD is not available. This could be because of some network connection errors. There is nothing we can do from the code side.
If you need support here, you can purchase one of the [support plans](https://active-directory-wp.com/shop-overview/).
