### ISSUE TITLE
German word/typo in Permissions tab

### ISSUE THREAD

**Issue by teejeer** [NeosIT/active-directory-integration2#2]
In the english localization of wordpress this plugin has a couple german words in the Permissions tab.

under Role equivalent groups it says Sicherheitsgruppe WordPress-Rolle.

Those should say Security Group and WordPress-Role
![screenshot from 2016-05-26 11 17 14](https://cloud.githubusercontent.com/assets/19541276/15583531/729ec5fe-2333-11e6-85ab-e5d6939743b3.png)

**Comment by schakko** [comment]
Thanks, fixed!
