### ISSUE TITLE
Can't connect with server

### ISSUE THREAD

**Issue by vi354** [NeosIT/active-directory-integration2#202]
Hello

I just change server and use a backup to restore. everything fine until the AD is connecting to the wrong IP address and Port.
So we should be getting from the  IP 94.46.183.99 (WordPress PTISP) to the IP 213.58.130.58 on port 389 (Moneris), but instead we are getting request on pot 443 on the  IP 213.58.130.57  from IP 94.46.183.99..

I have check all the configurations and it seems OK.  I have no idea why is that.
![image012](https://github.com/user-attachments/assets/91244598-5df0-42c1-9393-dbe107c53470)

**Comment by schakko** [comment]
I'll close this issue as this is specific to your environment. You should received an answer to your request via email. Please consider revoming the internal data and screenshot from this ticket.
