### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by katieharrington** [NeosIT/active-directory-integration2#205]
My org is on php 7.4.13 (Supports 64bit values) and doesn't plan on updating anytime soon - do I understand correctly that we should look for a different integration plugin?

**Comment by jpurpleman** [comment]
I'm in the same boat.  We're slow to update to the volume of code to review, change, and test and deploy.

We're still using version 2.3.8 which is the last version to support php 7.4.x

You can access it from the plugin repo on the advanced page.

https://wordpress.org/plugins/next-active-directory-integration/advanced/

**Comment by schakko** [comment]
You have to use the last version of the 2.x branch as @jpurpleman mentioned. We do not provide any support for PHP 7.4.
