### ISSUE TITLE
Fatal Error on Network Activation of NEXT AD Integration 2.0.7

### ISSUE THREAD

**Issue by requincreative** [NeosIT/active-directory-integration2#22]
I have been using Active Directory Integration 1.1.8 successfully but I recently changed to a MultiSite Installation and needed support for MultiSite.

I deactivated Active Directory Integration 1.1.8 and then installed Next Active Directory Integration 2.0.7. When I attempted to Network activate Next Active Directory I received the following error:

Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected ‘.’, expecting ‘,’ or ‘;’ in /var/www/html/forms/wp-content/plugins/next-active-directory-integration/classes/Core/Logger.php on line 22

I checked the file in question and line 22 is referencing the log file:

const LOG_PATH = NEXT_AD_INT_PATH . ‘/’ .’logs/debug.log’;
const FILE_CONVERSION_PATTERN_FILTER = ‘next_ad_int_file_conversion_pattern_filter’;
const ECHO_CONVERSION_PATTERN_FILTER = ‘next_ad_int_echo_conversion_pattern_filter’;

Any ideas?

**Comment by Tobi823** [comment]
Hi requincreative,

we acciendently use a PHP 5.6 feature (static scalar expressions for a constant). I will fix this bug as soon as possible.

You can replace
 const LOG_PATH = NEXT_AD_INT_PATH . '/' .'logs/debug.log';
in classes/Core/Logger.php line 22 with:
const LOG_PATH = "path/to/wp-content/plugins/next-active-directory-integration/logs/debug.log"
as workaround

**Comment by Tobi823** [comment]
Hi @requincreative,

the bug is now fix in version 2.0.8. Sorry for the inconvenience
