### ISSUE TITLE
Verify Credentials

### ISSUE THREAD

**Issue by kalakgl** [NeosIT/active-directory-integration2#25]
What have been changed from the "old" version to this "Next" version?
I can't have the Verify Credentials to work in this "Next" version, but are working in the "old" version.
Yes I know the username and the password are correct.
And no, I can't activate the log (as the error message tell me), because I can't save the settings without this verifying credentials.

**Comment by Tobi823** [comment]
Hi @kalakgl,
please add this to wp-content\plugins\next-active-directory-integration\classes\Adi\Init.php Line 158:
$enableLogging = true;

If you dont have the write permissions to wp-content\plugins\next-active-directory-integration\logs\debug.log, you can add your custom path to wp-content\plugins\next-active-directory-integration\classes\Adi\Init.php Line 152:
$customPath = 'my/custom/path/to/the/log/file';

And you are right. The user should be able to enable the logging at any time.

**Comment by FatSquirrel93** [comment]
Hello @kalakgl 
I have just read your comment. Please make sure, you press the plus-icon next to the _domain controllers_ input field inside the _Configuration -> Environment_.

![The settings need to look like this](http://i.imgur.com/i6P6ocU.png)

If you simply enter the domain controllers ip address into the input field and hit verify, that ip will not be used unless you have added it to the list by pressing the plus-icon next to it. 

We are aware that this is a big flaw in the user experience and have already started working on an improved version.
