### ISSUE TITLE
Sync thumbnailPhoto

### ISSUE THREAD

**Issue by plantjes** [NeosIT/active-directory-integration2#28]
Is it possible to sync the AD attribute "thumbnailPhoto"? 

This attribute doesn't sync because the length and the encoding (I think). 

More info: http://stackoverflow.com/questions/16937863/display-thumbnailphoto-from-active-directory-in-php?noredirect=1&lq=1

**Comment by MeissnerDa** [comment]
Hello plantjes, 
Next ADI does not support the import of thumbnail photos from the Active Directory to WordPress by default. If you would like us to add this feature for you please contact us via https://www.active-directory-wp.com/contact-us/

Have a nice day
MeissnerDa
