### ISSUE TITLE
SSO Authentication - No profile found for authentication

### ISSUE THREAD

**Issue by laughtonsm** [NeosIT/active-directory-integration2#29]
I am running WordPress on Windows Server 2012 R2 (IIS) with Next ADI 2.0.9.  I have configured the server for Kerberos Authentication and tested this to ensure that I am indeed authenticating via Kerberos.  I have also configured NextADI for SSO.  I can log in by supplying my AD user credentials in Username/Password fields.  However, SSO does not work.  in the debug og, I am seeing the following error:

2016-10-07 10:58:19 [ERROR] NextADInt_Adi_Authentication_SingleSignOn_Service::authenticate [line 102] User could not be authenticated using SSO. exception 'NextADInt_Adi_Authentication_Exception' with message '**No profile found for authentication**.' in C:\inetpub\wwwroot\isblog\wp-content\plugins\next-active-directory-integration\classes\Adi\Authentication\SingleSignOn\Validator.php:117
Stack trace:
#0 C:\inetpub\wwwroot\isblog\wp-content\plugins\next-active-directory-integration\classes\Adi\Authentication\SingleSignOn\Validator.php(62): NextADInt_Adi_Authentication_SingleSignOn_Validator->throwAuthenticationException('No profile foun...')
#1 C:\inetpub\wwwroot\isblog\wp-content\plugins\next-active-directory-integration\classes\Adi\Authentication\SingleSignOn\Service.php(84): NextADInt_Adi_Authentication_SingleSignOn_Validator->validateProfile(NULL)
#2 [internal function]: NextADInt_Adi_Authentication_SingleSignOn_Service->authenticate('')
#3 C:\inetpub\wwwroot\isblog\wp-includes\plugin.php(525): call_user_func_array(Array, Array)
#4 C:\inetpub\wwwroot\isblog\wp-settings.php(393): do_action('init')
#5 C:\inetpub\wwwroot\isblog\wp-config.php(89): require_once('C:\\inetpub\\wwwr...')
#6 C:\inetpub\wwwroot\isblog\wp-load.php(37): require_once('C:\\inetpub\\wwwr...')
#7 C:\inetpub\wwwroot\isblog\wp-login.php(12): require('C:\\inetpub\\wwwr...')
#8 {main}

Has anyone else encountered this?

**Comment by schakko** [comment]
@laughtonsm Based upon the given username in the REMOTE_USER environment variable, the required NADI profile is identified. Are you sure that you
- have selected the correct environment variable in the SSO tab of the NADI profile (REMOTE_USER should be the right)
- your IIS fills the REMOTE_USER variable
- the REMOTE_USER variable contains the username in the format $userPrincipalName@$upnSuffix
- your NADI profile contains your $upnSuffix

The given error does only occur when the assigned NADI profile can not be identified by the given username.

**Comment by laughtonsm** [comment]
Hi @schakko 

OK, so I can confirm that REMOTE_USER is set in  the SSO Tab
IIS is filling the variable with DOMAIN\USERNAME.

Not sure why this is, as I only have **Windows Authentication** enabled, and the only provider I am using is **Negotiate:Kerberos**

Any ideas?

**Comment by laughtonsm** [comment]
Just as an aside, I also have **Allow Down-Level Logon Name for login** enabled

**Comment by laughtonsm** [comment]
Hi @schakko.

Just an update.  I tried using the solution proposed on another issue posting, which involved using Helicon ISAPI_Rewrite 3 rewriting the REMOTE_USER variable to X-REMOTE-USER.  This also failed to work, using either X-REMOTE-USER or REMOTE_USER variables.  After a little experimentation, I discovered that the actual server vaiable being returned for use was neither of these.  Instead it was HTTP_X_REMOTE_USER.  I updated the NADI code in the Variable.php and Options.php files to match the server variable.  SSO now works as expected.

**Comment by FatSquirrel93** [comment]
Hi @laughtonsm 
I have just added this option to the SSO _Username variable_ Dropdown. Expect this fix to be included in the next release, hopefully tomorrow.

Thank you for reporting this issue. I will let you know, once the new version is released.

**Comment by FatSquirrel93** [comment]
Hi @laughtonsm 
We released the new 2.0.10 version yesterday. As promised, we added the HTTP_X_REMOTE_USER option to the SSO configuration.
Please update to the latest version and try using the new option.

Let us know, if the update fixed your problem. Thank you again, for reporting your issue.

**Comment by aquastern** [comment]
Hello, i get the same error  

"User could not be authenticated using SSO. No profile found for authentication" 

I think the SSO don't give the Suffix @xy.de with.

My REMOTE_USER give only my username without @xy.de because my Profiles on Wordpress is only the username. 
When i deactivate KrbLocalUserMapping On in Apache i get this error:

Local WordPress user 'user@xy.de' could not be found

because Wordpress user is only username. How can i solve this? Please help
