### ISSUE TITLE
Sync returns zero users

### ISSUE THREAD

**Issue by petterannerwall** [NeosIT/active-directory-integration2#31]
Hey!

For some reason my sync returns zero users in the specified group and then fails with the information below even though there are six users in the group. 

Is there any special permissions needed to sync? 

```

[INFO ] Start of Sync to WordPress 
[INFO ] LDAP connection is *not* encrypted 

<b>Warning</b>: ldap_control_paged_result_response(): Result is: Referral (10) in <b>D:\Sites\Intranet\wp-content\plugins\next-active-directory-integration\vendor\adLDAP\adLDAP.php</b> on line <b>966</b>
[INFO ] In group 'intra-read-employee' are 0 members. 
[ERROR] No possible users for Sync to Wordpress were found. 
```

I enabled the log and tried to sync again and got the following in the log. 

```
2016-11-02 09:21:12 [INFO ] NextADInt_Adi_Synchronization_WordPress::prepareForSync [line 159] Start of Sync to WordPress 
2016-11-02 09:21:12 [INFO ] NextADInt_Ldap_Connection::createConfiguration [line 101] LDAP connection is *not* encrypted 
2016-11-02 09:21:12 [INFO ] NextADInt_Ldap_Connection::findAllMembersOfGroups [line 529] In group 'intra-read-employee' are 0 members. 
2016-11-02 09:21:12 [ERROR] NextADInt_Adi_Synchronization_WordPress::synchronize [line 131] No possible users for Sync to Wordpress were found. 
```

**Comment by schakko** [comment]
Hi @petterannerwall,
are you sure that your base DN is specified correctly? See http://serverfault.com/questions/579881/domain-controller-returns-ldap-referral-for-its-own-domain .

**Comment by petterannerwall** [comment]
@schakko Seems like i got wrong information from my customer, but i managed to use Active Directory Explorer to fetch it myself. The Referral (10) error  then disappeared but the log still says zero users.

```
[INFO ] Start of Sync to WordPress 
[INFO ] LDAP connection is *not* encrypted 
[INFO ] In group 'intra-read-employee' are 0 members. 
[ERROR] No possible users for Sync to Wordpress were found. 
```

```
2016-11-02 12:56:36 [INFO ] NextADInt_Adi_Synchronization_WordPress::prepareForSync [line 159] Start of Sync to WordPress 
2016-11-02 12:56:36 [INFO ] NextADInt_Ldap_Connection::createConfiguration [line 101] LDAP connection is *not* encrypted 
2016-11-02 12:56:36 [INFO ] NextADInt_Ldap_Connection::findAllMembersOfGroups [line 529] In group 'intra-read-employee' are 0 members. 
2016-11-02 12:56:36 [ERROR] NextADInt_Adi_Synchronization_WordPress::synchronize [line 131] No possible users for Sync to Wordpress were found. 
```

As you can see in the image below there are 6 users in the group.

![image](https://cloud.githubusercontent.com/assets/5909669/19929699/ea2eb076-a104-11e6-891e-5c40965c59cd.png)

**Comment by schakko** [comment]
We have extended the logging functionality with the in-development version so you can more easily see why a security group could not be synchronized. We will push the changes in the next days.

Basically, the error with 0 members occur when the base DN is wrong.

In the meantime: is the security group a cascaded security group? meaning that intra-read-employee has a SG "my-read-employee" with 4 members?

**Comment by petterannerwall** [comment]
With SG i assume you mean Security Group? if se then no, there are a couple of Organisational Units above but i can't see that the groups are nested. 

Iv'e tried with all possible base dn's i could think of but none of them seemed to work. 

A censored version of the AD structure is below, taken from [Active Directory Explorer](https://technet.microsoft.com/en-us/sysinternals/adexplorer.aspx).

![image](https://cloud.githubusercontent.com/assets/5909669/19959764/2b5e2ea6-a1a9-11e6-8844-d76e992c3a1f.png)

Wouldn't OU=COMPANY,DC=COMPANYAD,DC=COMPANY,DC=SE be a correct base dn then?

**Comment by schakko** [comment]
Yes, I meant SG = Security Group.
The base DN ou=Company,DC=COMPANYAD,DC=COMPANY,DC=SE *should* be correct. It depends upon your AD settings.
My next guess is there is some other misconfiguration in your NADI settings. If not already done, please purchase an appropriate support license, open a ticket with reference of this GitHub issue and we can then proceed.

**Comment by petterannerwall** [comment]
@schakko Sure thing, il open up a issue!

**Comment by schakko** [comment]
With NADI 2.0.11 beta and base DN DC=COMPANYAD,DC=COMPANY,DC=SE this issue was fixed.
