### ISSUE TITLE
Allow Users to change their password

### ISSUE THREAD

**Issue by donfal71** [NeosIT/active-directory-integration2#34]
Hi,

First of all, thanks for you tremendous work. 

The plugin provides a lot of interesting and useful features, however, unless I misunderstood, It does not allow users to change their password (within the AD) through Wordpress. I think it could be a great feature, but It may be sensitive from a security point of view.

In my personal case, for instance, It could be useful. I developed a custom plugin to do that, but I thought it would be better if all was integrated in your plugin.

Thanks again for the nice work.

Sommy

**Comment by schakko** [comment]
Thank you for the response!

Your argument is one of the reasons we did not implemented a functionality to change passwords:

- Some customers are using WordPress with users having higher privileged domain permissions. If the WordPress instance gets hacked it could led to privilege escalation.
- The password must match the domain's password policy. If the user does not know *why* his password change fails or which requirements exists, the user's acceptance is low.
- You can specify multiple domain controllers. If you would have disabled Sync to Active Directory but would have enabled "Allow password change", the used domain controllers must not be a read-only replica. 
- Changing the password over LDAP requires a TLS connection which must be previously set up - not a real implementation issue but a task for the administrator

I will not exclude the possibility that we will implement the feature someday but it is currently not on our agenda.

**Comment by donfal71** [comment]
Ok. I guessed you thought about that before but the reasons why you didn't implement the feature are good.

So I will extend your plugin through another one in order to get the job done. 

Have a nice day.

**Comment by schakko** [comment]
One note: with 2.0.11 (possible released at the mid/end of November) we will publish the API so you can re-use the adLDAP classes.

**Comment by donfal71** [comment]
Ok, i'll follow you then. Thanks for your message.

Good luck.

2016-11-10 11:46 GMT+01:00 Schakko <notifications@github.com>:

**Comment by ricostone** [comment]
Hi ! i know that is an old thread but i'm interested in this feature too. Is it possible to achieve this nowaday with the api or with an integrated feature ?
Thanks !

**Comment by schakko** [comment]
@ricostone Hi, after this issue we had internally talked about it and in the end decided against it.

**Comment by ricostone** [comment]
Thank you for your fast answer, that's clear :)
