### ISSUE TITLE
Profile Page is deactivated + Cant create new profile

### ISSUE THREAD

**Issue by idkme** [NeosIT/active-directory-integration2#35]
Hello guys,
I really need your help. Ive been trying to get this work for many hours. 
I got a multisite installation and activated it for all but in profile options page I cant selct any profile. When I click on "Create new profile" nothing happens. In a site with the plugin the settings page is deactivated, so I cant write in any field. 
I recently tried another browser and pc. Im logged in with administrator account, but tried it with another and nothing changed. I thought its maybe a fail with the rights but everything should be ok.
Maybe you know something about this.

Thank you.

**Comment by schakko** [comment]
Can you please check if there is a JavaScript error by using your webbrowser console. Besides that: make sure that your website is added to local Intranet zone if you are using the Internet Explorer. Otherwise the execution of JavaScript could be prevented.

**Comment by idkme** [comment]
Sure. Im using Firefox atm.
`Failed to load resource: the server responded with a status of 403 (Forbidden)
2https://127.0.0.1/wp-content/plugins/next-active-directory-integration/js/app/app.config.js?ver=1.0 Failed to load resource: the server responded with a status of 403 (Forbidden)
https://127.0.0.1/wp-content/plugins/next-active-directory-integration/js/app/profile-options/controllers/password.controller.js?ver=1.0 Failed to load resource: the server responded with a status of 403 (Forbidden)
angular.min.js?ver=1.0:116 Error: [$injector:unpr] http://errors.angularjs.org/1.5.3/$injector/unpr?p0=%24resultProvider%20%3C-%20%24result%20%3C-%20DataService
    at angular.min.js?ver=1.0:6
    at angular.min.js?ver=1.0:43
    at Object.d [as get] (angular.min.js?ver=1.0:40)
    at angular.min.js?ver=1.0:43
    at d (angular.min.js?ver=1.0:40)
    at e (angular.min.js?ver=1.0:41)
    at Object.instantiate (angular.min.js?ver=1.0:41)
    at Object.<anonymous> (angular.min.js?ver=1.0:42)
    at Object.invoke (angular.min.js?ver=1.0:41)
    at Object.$get (angular.min.js?ver=1.0:38)`

**Comment by schakko** [comment]
This looks like a problem with your webserver. The 403 is returned by Apache/IIS. Even with a logged out WordPress user you can retrieve the JavaScript files.
Check your access.log/error.log and any .htaccess file for blocking the JavaScript files.

**Comment by idkme** [comment]
Maybe I should write what the solution was: 
In the .htaccess file Wordpress restricted alls files which got a "config" or "password" in it. So the files were not allowed to read. So allowing the specific files helped us to get Next ADI working.

Thank you.

**Comment by schakko** [comment]
Thank you for the response. Have you added the .htaccess entries by yourself before?

**Comment by idkme** [comment]
No I didnt. But there are some security plugins. I think one of them changed the file.

**Comment by mikeboltonca** [comment]
Can anyone tell me what I should be adding to my htacccess file exactly?
Thanks for your support!
