### ISSUE TITLE
Multiple suffixes -> wrong brute force protection

### ISSUE THREAD

**Issue by ReneLuecking** [NeosIT/active-directory-integration2#36]
If multiple suffixes are set, the counter for failed logins is incremented for each suffix. So if 3 suffixes are set, the counter is set to 3 at one login attempt. It follows that the BruteForce protection is already triggered on the first login, if this is left with the default value of 3.

**Comment by schakko** [comment]
Thanks for the issue. We had a discussion earlier today about this problem. There are a few options to solve it but none of them is really satisfying. In addition to that the current BFP does not work reliable. I let you know when we have come to an agreement how to fix the BFP.

**Comment by MeissnerDa** [comment]
Hello @ReneLuecking,
with NADI 2.0.14 the BFP was flagged as deprecated. We plan on removing it completely with NADI 2.1.1.

Best regards,
meissnerDa
