### ISSUE TITLE
Missing "%" in notification email body

### ISSUE THREAD

**Issue by ReneLuecking** [NeosIT/active-directory-integration2#37]
You missed a "%" in line 31 of _classes\Adi\Mail\Message.php_ so the email address of the blocked user is always "s":
This account is associated with "%s %s" and the email address **"s"** -> This account is associated with "%s %s" and the email address **"%s"**.

**Comment by schakko** [comment]
Thank you for bug report @ReneLuecking ! We will fix it ASAP.

**Comment by FatSquirrel93** [comment]
Hey @ReneLuecking 
We have just released the 2.0.11 version. See https://github.com/NeosIT/active-directory-integration2/commit/ad2aa904b38a4762202ca329bb3d3b1dcc63b06b for the changes.

Please update the plugin and lets us know if your problem has been fixed.
Thanks for reporting your issue.
