### ISSUE TITLE
thumbnailPhoto sync

### ISSUE THREAD

**Issue by gumida** [NeosIT/active-directory-integration2#38]
It's more of a feature request than an issue:

Adding a sync option for the attribute "thumbnailPhoto" would be a great feature.
Upload and store your user's pictures to AD and sync them back as profile pictures in WordPress.

Have you thought about such a feature?

**Comment by schakko** [comment]
Hi @gumida ! We had this already in our backlog :-)
We will publish the profile picture synchronization (currently only from AD to WordPress not vice versa) as a premium NADI extension with the next version.

**Comment by gumida** [comment]
Hello @schakko,
I'm really looking forward to this update. Is there any timeline for the next version? ;-)

**Comment by schakko** [comment]
We have planned to release 2.0.11 in the next week. At the moment it depends highly upon our sick leave :-/
