### ISSUE TITLE
Seconds in Block Message

### ISSUE THREAD

**Issue by ReneLuecking** [NeosIT/active-directory-integration2#39]
You count from 35 down to 0 in your block message (`'timeLeft' => $timeLeft + 5`), but the time in the message is initially set to 30 (`<span id='secondsLeft'>$timeLeft</span>`). So its a bit confusing if it counts like this: 30, 34, 33, ....

Maybe you should change the `$timeLeft` in the beginning of the function to `$timeLeft + 5`

File: _classes/Adi/Authentication/Ui/ShowBlockedMessage.php_
Function: **showBlockMessage**

**Comment by FatSquirrel93** [comment]
Hey @ReneLuecking 

We have fixed the issue you were describing. 5e73a88
