### ISSUE TITLE
Duplicate user conversion?

### ISSUE THREAD

**Issue by brocheafoin** [NeosIT/active-directory-integration2#40]
Hello there. First of all, thank you for the extremely useful plugin. We do have an issue with it, though.

Our multisite installation has existed for a year and half before we decided to implement SSO with your plugin. Therefore, a number of users already have local WordPress accounts. At this time, the approach you recommend is to prevent the creation of new AD users with the same email addresses as local users, which seems reasonable enough, but it locks these users into the old user/password paradigm.

The **ideal** solution would be for these users to be _converted_ to AD users on first SSO auto-login attempt. This way they could connect transparently and still have access to the content they have already created. I understand this poses additional questions (what about roles, for example?) but I was wondering if this is something you've ever thought about.

Thanks!

**Comment by brocheafoin** [comment]
I wanted to clarify our use case, after having played a little bit more with the User and Permissions settings. Here goes:

- WordPress network, with about a hundred local users created before Next ADI
- AD Domain with a few thousand users
- Most sub-sites would use this kind of configuration:
    - Auto Create User: off
    - Role Equivalent Groups: off
- A few sub-sites would use this kind of configuration:
    - Auto Create User: on
    - Role Equivalent Groups: yes
- Users could be members of both types of sites

In other words, for most sites, we want a short list of users which we manage inside WordPress, while for a few sites, we want user creation and role attribution to be done on the fly from AD because they will have hundreds of users and role/group changes.

In theory, this should be possible with Next ADI, but in practice, it may be one of those edge cases you could not envision when creating the plugin. By the way, if you feel this kind of question warrants premium support, I'd like to know so I can cajole my customer into purchasing a license. Thanks!

**Comment by brocheafoin** [comment]
Furthermore, this may be related to the fact that our previously created local WP users have email addresses as login names. I'm making additional tests in a smaller separate instance and will report back.

**Comment by brocheafoin** [comment]
OK, the login names was a wild goose chase. We no longer use email addresses for these and my test install works/does not work in exactly the same way as our production site. Please disregard the previous comment. Thanks!

**Comment by MeissnerDa** [comment]
Hello brocheafoin,
we are currently taking a look into this matter and will discuss it in our team. I will report back to you in the next week. 

Greetings 
MeissnerDa

**Comment by brocheafoin** [comment]
Thanks for the update, @MeissnerDa ! I've run additional tests on a stripped down installation and it turns out the user_login names were indeed part of the problem. Here are the standard formats in our AD:

* sAMAccountName: GivenName.LastName
* userPrincipalName: givenname.lastname@domain.tld

These formats include uppercase characters and periods (dots), both of which are forbidden characters for user_login in a multisite installation. All our local users were created with the following format:

* user_login: givennamelastname

In the current state, what happens is this:

1. NextADI tries to find an existing WP user with a GivenName.LastName user_login, fails
2. NextADI then tries to create the WP user to match the AD user, but fails because the email address is already in use

If I change the WP user_login to a format equivalent to the one used in AD, NextADI actually does pretty much what I described earlier, i.e. "converts" the existing WP user to an ADI user.

In the end, I don't think this is an issue you can fix per se, as it is and will be very specific to each installation. Maybe a warning in the documentation about restricted characters for user_login in multisite installations?

**Comment by MeissnerDa** [comment]
Hello brochefoin, 
I tried to reproduce your problem but I was not able to do so. I created an AD user with 

sAMAccountName: GivenName.LastName
userPrincipalName: givenname.lastname@domain.tld

and was able to synchronize the user to WordPress without any problem. I was also able to create the user via "Automatic user creation". The "user_login" was set to "givenname.lastname" as well. I tested it with the current stable release on WordPress and with our dev version. 

I agree with you that we should add a hint in our documentation that WordPress only supports a-z lowercase only as user_login by default.

greetings
MeissnerDa

**Comment by brocheafoin** [comment]
Hello @MeissnerDa!

To be 100% accurate, it is only in **multisite** WordPress that the character restrictions for the username are enforced. In single site install, our AD setup would not have caused any issue.

Thanks for taking the time to test this. I will close this issue.
