### ISSUE TITLE
AD password issue

### ISSUE THREAD

**Issue by darrencon** [NeosIT/active-directory-integration2#41]
I am able to sync to wordpress sucessfully and I can then see the ad users created in wordpress after a sync. The problem is that the synced AD user cannot login? It says the password is incorrect? It does this for all the synced users.

If I then allow password change in wordpress for the ad user and then change the password to the AD password in wordpress, then the user can login?

I dont want to allow password changes in wordpress.... please help me to resolve the issue of why it is not syncing the users AD password on creation?

**Comment by FatSquirrel93** [comment]
Hey @darrencon 
When you try to log in, please make sure you either add the suffix (@company.com) or you configure your suffix in the Plugin settings.

If this does not resolve your issue, please enable logging and check the log file. You can always attach any log output to this issue.

I hope this fixes your issue.

**Comment by darrencon** [comment]
I have configured the suffix in the plugin settings. I cant see why the users password wont work. I have attached the log file. Please help

[debug.txt](https://github.com/NeosIT/active-directory-integration2/files/738418/debug.txt)

**Comment by darrencon** [comment]
Are you referring to this one? Cause thats the error log I sent you 
![nextad](https://cloud.githubusercontent.com/assets/25427644/22420110/4dee4fc0-e6e9-11e6-95b5-2b0d6714c554.JPG)

**Comment by FatSquirrel93** [comment]
Yes that´ correct. But you send me the log output during the _Sync To WordPress_ process. What we need, is the output during an actual login attempt. It should narrow down the possible issue.

**Comment by darrencon** [comment]
Ok now I understand. So What I did now is clear the contents of the log file and saved and closed it. I then tried to login got the samme incorrect password error. So now if I go back the the logfile, it is empty?

**Comment by FatSquirrel93** [comment]
When logging in using our plugin, the logfile can not be empty. There should be at least a few lines.

Are you by any chance using a custom theme? Some themes or plugins use a different login screen.
Are you using the default WordPress login screen?

**Comment by darrencon** [comment]
Yes I am using a custom theme and I am not using the default wordpress login screen

**Comment by FatSquirrel93** [comment]
We can not ensure full functionality when using themes. We do not support custom login forms. It would require changes for every single theme.
What theme are you using? We do offer the following themes as premium extensions:
WooCommerce
Ultimate Member

If you need to get a custom implementation, you need to contact us at https://active-directory-wp.com/contact-us/

**Comment by darrencon** [comment]
If I had known that then I would not have bought a support license as everything worked fine even the test authentication.

We are using buddyapp theme

**Comment by FatSquirrel93** [comment]
If you have bought a support license, please contact us using the https://active-directory-wp.com/ site.

**Comment by darrencon** [comment]
Why must I do that if you dont support custom login forms?
