### ISSUE TITLE
Plugin is automatically deactivating.

### ISSUE THREAD

**Issue by JRhyne** [NeosIT/active-directory-integration2#42]
The plugin randomly deactivates causing users to not be able to log in.  Nothing is showing in Apache, Wordpress, or plugin log files.

**Comment by MeissnerDa** [comment]
Hello JRhyne,
Can you tell me if you have other plugins activated ?

greetings
MeissnerDa

**Comment by FatSquirrel93** [comment]
Hey @JRhyne 
do you have any news on the problem? We were not able to reproduce the issue you are describing. 

Please let us know if you have any custom themes or plugins installed. In most cases, a potential problem is caused by other plugins, interfering with NADI.

**Comment by JRhyne** [comment]
We found out this was going on because we were working off the same remote database with different site urls.

**Comment by chadhayton** [comment]
@JRhyne,
We are having the same problem.  Was their a resolution to this issue?
