### ISSUE TITLE
NTLM SSO not working with claims based authentication

### ISSUE THREAD

**Issue by rgottsch** [NeosIT/active-directory-integration2#44]
I had Wordpress installed on IIS where SharePoint was also enabled, and SharePoint enabled claimsbased authentication, so my REMOTE_USER Looks like this `claims|domain\username` which of course broke the NLMT SSO.

I have rewritten the setNetbiosName function of Credentials.php to look something like this:

```
	public function setNetbiosName($login) {
		$parts = explode("\\", $login);
		if (sizeof($parts) >= 2) {
			
			// check if the username has claims prefixed, then the REMOTE_USER looks like this 0#.w|domain\username
			$parts_claims = explode ("|",$parts[0]);
			if (sizeof($parts_claims)>=2)
				$this->netbiosName = strtoupper($parts_claims[1]);
			else
				$this->netbiosName = strtoupper($parts[0]);

		}
			
	}
```

not sure if it is worth including in the official build - it is a strange configuration, but it is something that could possible be seen in the wild with IIS and SharePoint installed.
(also see https://msdn.microsoft.com/en-us/library/office/jj163913.aspx for some Background on the 0#.w part of the username)

**Comment by MeissnerDa** [comment]
Hello rgottsch,
Thank you for informing us about this case. We will discuss this within our team and we will inform you, if we are going to include it in the offical build.

greetings
MeissnerDa

**Comment by MeissnerDa** [comment]
Hello @rgottsch, 
we added this to our intern issue tracker and plan on including it with the release of NADI 2.1.1.

Best regards,
meissnerDa
