### ISSUE TITLE
Automatically add users via CRON task

### ISSUE THREAD

**Issue by cibretagne** [NeosIT/active-directory-integration2#45]
Hello,

We use your plugin and are very satisfied, thank you for that.

However, we would like to know if you plan to add this feature in future updates:

Automatically add into Wordpress the existing users from Active Directory but not yet in Wordpress via the CRON task "Sync to WordPress"

Thank you for your answer.

Have a good day.

**Comment by MeissnerDa** [comment]
Hello cibretagne, 
we are glad to hear that you like our plugin. In NADIs current state it should already be possible to add/update users from the Active Directory to/in WordPress. You can do this by setting up a cronjob calling your "Sync to WordPress" curl.

greetings
meissnerDa

**Comment by FatSquirrel93** [comment]
Please check our official documentation for any further details https://active-directory-wp.com/docs/Usage/index.html

You could simply create a cronjob executing your wget or curl request. This would trigger a Sync to WordPress or Sync to AD.
