### ISSUE TITLE
"Test authentication" lies!

### ISSUE THREAD

**Issue by johanruda** [NeosIT/active-directory-integration2#46]
Hey there, devs!

I'm trying to get your awesome plugin to work, but I'm having some problems. Not sure it's a bug but it feels like it. I've set up a test user in AD. When I try the "Test authentication" feature, it literally says "User logged on", but when I actually try to actually log on with that account on our site, I get a "Invalid account" or something similar. Not sure what it says in English as I'm using a Swedish install of Wordpress.

When I try with my personal account, it works though so I'm just confused as to what I'm doing wrong.

Logs with both login attempts below. 

Thanks in advance!

[log.txt](https://github.com/NeosIT/active-directory-integration2/files/785337/log.txt)
[log_success.txt](https://github.com/NeosIT/active-directory-integration2/files/785350/log_success.txt)

**Comment by MeissnerDa** [comment]
Hello johanruda,
please take a look at our documentation at https://active-directory-wp.com/docs/Getting_Started.html .
If you require further assistance please buy a support license at https://active-directory-wp.com/shop-overview/ and send us your support request there. 

Greetings
MeissnerDa
