### ISSUE TITLE
require_once("functions.php") - index.php

### ISSUE THREAD

**Issue by rkorzen** [NeosIT/active-directory-integration2#47]
Hi, 

I saw in my last project some unusual behavior. Its seems that 

    require_once("functions.php"); //line 29 of index.php

in index.php of Next Active Directory Integration plugin in fact call some other functions.php than this from plugin (next messages in trace were connected with functions in custom theme ). I'm not good in php and spent long time to fiugure what's the problem. Soo.. after change of file name both in directory and in require_once - problem dissapear.. But i noticed that more elegant and maybe universal solution will be like this:

    require_once(dirname(__FILE__)."/functions.php");

maybe it will be helpfull for someone

**Comment by FatSquirrel93** [comment]
Hey @rkorzen 

thank you very much for reporting your findings.
We have just discussed this issue and we will be testing it now.

If this proves to be correct, we will include it inside tomorrows next release.

**Comment by FatSquirrel93** [comment]
Fixed version 2.0.13 released.
