### ISSUE TITLE
SSO doesn't work because the sAMaccountname and userPrincipalName differ

### ISSUE THREAD

**Issue by CupCoffee** [NeosIT/active-directory-integration2#48]
Hi,

I have been getting the following error

` Attributes for '$username': could not be loaded. Does the sAMAccountName or userPrincipalName exist? Is the provided base DN valid? `

I have read the documentation about this error and made sure the Base DN is set correctly. Unfortunately this didn't make any difference.

I dived into the code and i found that the Adi_Authentication_SingleSignOn_Service uses the user's sAMaccount name to retrieve the user's attributes. This succeeds. Then it tries to authenticate using the parents class authenticate method (Adi_Authenticaton_LoginService). However, this fails because this time it uses the userPrincipalName which in my case often differs from the sAMaccount name.

When i change the attribute it uses for the createUpnCredentials to samaccountname it works.

Is this a faulty AD configuration?

**Comment by MeissnerDa** [comment]
Hello @CupCoffee ,
for NADI the samAccountName + Account Suffix has to be equal to the UPN if you wish to be able to login using the samAccountName only. You also have to add the suffix to the "Account Suffix" option. 

Best regards,
meissnerDa
