### ISSUE TITLE
Empty Base DN

### ISSUE THREAD

**Issue by ReneLuecking** [NeosIT/active-directory-integration2#49]
Today I updated from 2.0.11 to 2.0.13. Now I cannot save my settings anymore, because the Base DN is empty. In my case the Base DN must be empty, because we use the global catalog in my company with four different domains in it. If i specifiy a Base DN, only one of the domains can be accessed and many of my coworkers cannot login.

**Comment by MeissnerDa** [comment]
Hello @ReneLuecking, 
Thank you for reporting this problem we will add this to our intern issue board for NADI 2.1.1 . 

Best regards,
meissnerDa

**Comment by MeissnerDa** [comment]
Hello @ReneLuecking,

we will fix this problem with the next release of NADI (2.1.1) which will approximately be released in the next days.

Best regards,
meissnerDa
