### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by teejeer** [NeosIT/active-directory-integration2#5]
I would really like to bring this over to our production systems. Is it in a state where I can do so? Minor bugs don't bother me too much. As long as the AD auth/Role mapping for Administrator/Contributor/Editor/Subscriber work then I am happy. This seems to be the case with my testing.

**Comment by schakko** [comment]
From our point of view there is only big issue open. But this belongs to multi-domain handling which is just an experimental feature. Even if ADI2 is still labeled as "Beta" it should already work in a production environment.

**Comment by teejeer** [comment]
We'll I've got it on our production systems. Thanks for your hard work.

**Comment by Tobi823** [comment]
The plugin was released on https://wordpress.org/plugins/next-active-directory-integration/ and is now production ready.
