### ISSUE TITLE
How to configure SSO

### ISSUE THREAD

**Issue by no-name12363** [NeosIT/active-directory-integration2#50]
Hello,

I'm running an intranet website with wordpress via Apache (xampp on an Windows Server) and want to login with SSO.
I allready installed Next Active Directory Integration and connected it with the LDAP Server and I can login with our domain users.
But I don't know how to configure SSO.
Can you help me with that?

Kind regards

**Comment by schakko** [comment]
Hey there,
sorry, but this is out of scope of this Github project. If you need professional support you can take a lookt at https://active-directory-wp.com/service-for-active-directory-and-wordpress/ .

**Comment by sksoftwaredev** [comment]
I'm told that in order to make SSO work you have to use Windows' Internet Information Service (IIS) to host the site instead of Apache.

I realize I'm posting this well over a year after it was originally asked, but I'm curious - did you ever get it working?
