### ISSUE TITLE
wrong sAMAccountName to retrieve groups when not sAMAccountName@domain.tld

### ISSUE THREAD

**Issue by matll42** [NeosIT/active-directory-integration2#51]
sAMAccount is deduced from login, but it's not the right one.

in my AD I've got :
toto@my-first-domain.com (real sAMAccountName : toto1) in authorized group
toto@my-second-domain.com (real sAMAccountName : toto)

When I connect with toto@my-first-domain.com, it deducts sAMAccountName toto, get it's groups so it's not in authorized group and can't login.

On Test authentication.
Credentials={login='toto@my-first-domain.com',sAMAccountName='toto',userPrincipalName='toto@my-first-domain.com',netbios=''}' with authenticatable suffixes: '@my-first-domain.com'.

Is it possible to use UPN instead of sAMAccount for query ? can't find such an option to do that.

The problem is existing in ADI and nextADI.

**Comment by MeissnerDa** [comment]
Hello @matll42,

if you disable the option "Use sAMAccountName for newly created users" the UPN will be used.

Best regards
meissnerDa

**Comment by matll42** [comment]
thanks, I'll try
