### ISSUE TITLE
Custom User Role Management Issue

### ISSUE THREAD

**Issue by jebu1104** [NeosIT/active-directory-integration2#54]
I had some users previously synced with AD but then we decided to use Custom User Role Management to assign them a new role of Departments however some of those users are not keeping the role. I have Clean Existing role check but when I save my settings in Custom User Role Management it shows several users with an empty role even though i had set them to "Departments". It looks like it saves fine and when I refresh the page they aren't there.

**Comment by MeissnerDa** [comment]
Hello @jebu1104,
please contact us via https://active-directory-wp.com/support/ so we can take a look at your problem.

Best regards
meissnerDa
