### ISSUE TITLE
Drop in replacement for wp_authenticate?

### ISSUE THREAD

**Issue by techypaul** [NeosIT/active-directory-integration2#56]
Hi,

Through a custom plugin, we are using:

$user = wp_authenticate( $username, $pwd );

Assuming this plugin is active, will the plugin replace this function, or does it provide a replacement (or maybe, neither - and it won't work at all)?

Thanks,
Paul.

**Comment by MeissnerDa** [comment]
Hello @techypaul,

in NADI we hook the following filter in order to react to an authentication https://codex.wordpress.org/Plugin_API/Filter_Reference/authenticate . Then NADI takes those credentials and tries to authenticate the user against the AD. 

Best regards,
medan123
