### ISSUE TITLE
2.1.0 Logger.php error

### ISSUE THREAD

**Issue by chatito28** [NeosIT/active-directory-integration2#58]
Parse error: syntax error, unexpected '.', expecting ',' or ';' in C:\inetpub\wwwroot\wp-content\plugins\next-active-directory-integration\classes\Core\Logger.php on line 28

**Comment by MeissnerDa** [comment]
Hello @chatito28,
can you tell me which PHP version you are using ? 

Best regards,
meissnerDa

**Comment by chatito28** [comment]
5.4.24

**Comment by MeissnerDa** [comment]
Hello @chatito28,
NADI requires atleast PHP >= 5.6

Best regards,
meissnerDa

**Comment by schakko** [comment]
I am closing this issue. As already stated, we are requiring 5.6 since a longer period and 5.4.24 is EOL. @chatito28 please upgrade to PHP 5.6 :-)
