### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by hogsim** [NeosIT/active-directory-integration2#6]
After updating on the latest version I got this error message : 
Fatal error: Uncaught Twig_Error_Loader: Unable to find template "option/element/domainsid.twig" (looked into: /var/www/html/wp-content/plugins/active-directory-integration2/views) in "blog-options-page.twig" at line 14. in /var/www/html/wp-content/plugins/active-directory-integration2/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:194 Stack trace: #0 /var/www/html/wp-content/plugins/active-directory-integration2/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(138): Twig_Loader_Filesystem->findTemplate('option/element/...') #1 /var/www/html/wp-content/plugins/active-directory-integration2/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Filesystem->getCacheKey('option/element/...') #2 /var/www/html/wp-content/plugins/active-directory-integration2/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('option/element/...', NULL) #3 /var/www/html/wp-content/plugins/active-directory-integration2/twig/cache/c1/f2/419ea130d7db9c36bf68a8dc457b1006bf305ed0dc0a1b8bf5e89c8df9d9.php(170): Twi in /var/www/html/wp-content/plugins/active-directory-integration2/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 194

**Comment by schakko** [comment]
@hogsim sorry about that. The latest commit should fix the problem.

**Comment by hogsim** [comment]
Thanks :)
