### ISSUE TITLE
Import to Wordpress imports only some OUs

### ISSUE THREAD

**Issue by maccored** [NeosIT/active-directory-integration2#62]
Hi - Hopefully theres something simple here that I am missing.

Im trying to import in users from AD to Wordpress using the NExt Active Directory Integration plugin.  All users come in fine when I use id:513.  The issue occurs when I try to match AD OUs with Wordpress user categories. Some work fine.  ICT for example, will properaly assign everyone in the ICT OU in AD to the IT category in Wordpress.  Others - Arts for example, wont assign.  Both OUs are identical.

What Ive found is, in the the Environment area of the configuration for the plugin, I can verify if I set my Base DN to the OU that includes all the users.  I can also verify if I extend that and include the OU for ICT.  If though, I change ICT to Arts, it doesnt verify and if I try to then run the import I get the error:

"SID of user '[my admin account]' could not be retrieved. Is the base DN correct? "

So - to check the base DN, I go to Active Directory, rightclick the Arts OU, go to Properties etc and check the Distinguished Name, which gives the Base DN.  I am using the correct one.

The error tells me I am not using the correct Base DN though and this (I assume) is why that particular OU (and the others Im having issues with) wont import.

Is there any way I can fix this?

many thanks

**Comment by schakko** [comment]
This is not how NADI nor Active Directory works. The base DN is the upper most OU in your organization in which all of your users reside. In your case something like *DN=myorganization,DN=com* or the special OU *OU=Users,DN=myorganization,DN=com* which includes all other users.

Just use one of these OUs and assign the proper Active Directory security groups to the WordPress roles.

**Comment by maccored** [comment]
cheers schakko.  I understand what you mean as I have been using the correct base DN. Described above is a trouble shooting method I was trying to figure it out.  As I say, using the proper base DN I can import all users, but only some  security groups get assigned and others don't.  All security groups have the same settings so Im just trying to figure out why whats happening
