### ISSUE TITLE
Error when logging in: Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by PavelVanecek** [NeosIT/active-directory-integration2#63]
Hi,

I am attempting to migrate from ADI to NextADI but I am running into an issue. When I attempt to log in, it takes a _long_ time and after that I can see login page again with an error:

```
Warning: sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/plugins/next-active-directory-integration/classes/Adi/Authentication/LoginService.php on line 622

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/next-active-directory-integration/classes/Adi/Authentication/LoginService.php:622) in /var/www/html/wp-includes/pluggable.php on line 920

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/next-active-directory-integration/classes/Adi/Authentication/LoginService.php:622) in /var/www/html/wp-includes/pluggable.php on line 921

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/next-active-directory-integration/classes/Adi/Authentication/LoginService.php:622) in /var/www/html/wp-includes/pluggable.php on line 922
```

And:
```
ERROR: Cookies are blocked due to unexpected output.
```

Now I guess that it all is caused by the first printed Warning; which made it not possible to send cookies which broke the login process. I could probably workaround by disabling warnings, but I would prefer a real fix. Can you please suggest?

My environment:
- PHP 7.2.0
- WordPress 4.9.1
- NADI 2.1.0

**Comment by MeissnerDa** [comment]
Hey @PavelVanecek,

I upgraded my test machine to the latest PHP 7.2.0 and I was able to reproduce the sizeOf() warning. However I was not able to reproduce 

`Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/next-active-directory-integration/classes/Adi/Authentication/LoginService.php:622) in /var/www/html/wp-includes/pluggable.php on line 920

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/next-active-directory-integration/classes/Adi/Authentication/LoginService.php:622) in /var/www/html/wp-includes/pluggable.php on line 921

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/next-active-directory-integration/classes/Adi/Authentication/LoginService.php:622) in /var/www/html/wp-includes/pluggable.php on line 922`

We will fix the sizeOf() warning with the next NADI release. 

Best regards,
meissnerDa
