### ISSUE TITLE
Powershell Cron

### ISSUE THREAD

**Issue by nemchik** [NeosIT/active-directory-integration2#64]
https://active-directory-wp.com/docs/Usage/How_to_add_a_cron_job_on_Windows.html

The page above provides instructions on adding a cron job using wget, which is all fine and good, but you can do this much easier on Windows using Powershell (which is preinstalled on most Windows server systems since 2008).

In the second screenshot where it asks for `Program/script` simply type `powershell` and for `Add arguments (optional)` you would enter `-ExecutionPolicy unrestricted -Command "Invoke-WebRequest -Uri ###SERVERURLL###/wp-admin/admin.php -Method POST -Body @{'next_ad_int-task'='sync-to-wordpress';'auth-code'='###TOKEN###'}"`

This would be very handy to add to the instructions https://github.com/NeosIT/active-directory-integration2/blob/master/views/sync-to-ad.twig#L7 and on the page I linked at the top.

**Comment by FatSquirrel93** [comment]
Hey @nemchik 
thank you very much for letting us know about this very handy alternative!
I will be checking this process. 

Thank you for your support 👍

**Comment by FatSquirrel93** [comment]
Hey  @nemchik 
I have just tested your suggestion and updated the official documentation. 
https://active-directory-wp.com/docs/Usage/How_to_add_a_cron_job_on_Windows.html now includes your contribution!

The next release should also include instructions on the _Sync to AD_ and _Sync to WordPress_ pages for using PowerShell. 

We are very thankful for your contribution. Keep up the good work!
