### ISSUE TITLE
showing active directory fields in user profile

### ISSUE THREAD

**Issue by SamanthaSt** [NeosIT/active-directory-integration2#66]
Hello,
I am completely new to Wordpress and i already spent many hours searching for a solution.

With the "Attributes" section I was able to get the needed AD fields saved in the wp_usermeta table.
Now what i want to do is show those additional information, for example the telephone number, in the users profile. Is that possible and if yes how?

It would be great if it would work with a plugin, but in the worst case it would be fine to code myself. 
I already saw solutions where  they used the get_user_meta() function, but none of those really worked for me.

Thank you already for your your help. I hope everything makes sense, I am just getting started as a programmer xD

**Comment by MeissnerDa** [comment]
Hello @SamanthaSt,

you can simply display the attributes you configured at the NADI configurations "AD attributes" tab in the user profile by checking the checkbox "View in User Profile" in the row of the attribute you would like to be displayed.

Best regards,
meissnerDa

**Comment by SamanthaSt** [comment]
Hy @MeissnerDa 
thank you for your answer. This function is just not really working, maybe because I use Buddypress.
I saw that the desired function is included in the premium extension, so I will just purchase them.

Best regards,
Samantha S.
