### ISSUE TITLE
Enabling NExt AD plugin with suffix @blahblah.local. Now get 500 website not found

### ISSUE THREAD

**Issue by Madcowpro2** [NeosIT/active-directory-integration2#67]
So I downloaded, installed, configured and everything was fine with my wordpress site. I added my local domain suffix and now I get 500 webserver cannot be reached. Any ideas?

**Comment by MeissnerDa** [comment]
Hello @Madcowpro2 ,

please take a look in your apache error_log and the "nadi-debug.log" if you already activated logging. Also please take a look at our documentation https://active-directory-wp.com/docs/Getting_Started.html.

Best regards,
meissnerDa
