### ISSUE TITLE
Errors occur if Twig cache directory is not writable

### ISSUE THREAD

**Issue by Munnday** [NeosIT/active-directory-integration2#7]
I'm attempting on running the application via IIS (not sure if this issue exists on other web platforms)

When Activating:

> The plugin generated 3 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

When browsing to any of the Setting pages for the plugin, then are blank

**Comment by Munnday** [comment]
Resolved - file permissions.
The WordPress environment is locked down - manual updates needs to happen, wp-content isn't writable.

Twig needs to create content on the fly so i needed to modify security permissions to allow some write access for the plugin to function

**Comment by schakko** [comment]
This is something we have to handle. In addition to that the installer must check the writable flag of the twig cache directory.

**Comment by schakko** [comment]
@MeissnerDa How much impact would it have to disable the whole Twig cache (http://twig.sensiolabs.org/doc/api.html#environment-options)? In the end the configuration of does only change a few times and must not be included in every Wordpress call.
