### ISSUE TITLE
BuddyPress Simple Attributes Extension

### ISSUE THREAD

**Issue by danieray** [NeosIT/active-directory-integration2#70]
I have installed the BuddyPress Simple Attributes extension and followed the instructions to map the attributes to custom fields. The data is still not displaying on the member directory page. Am I missing something?

**Comment by danieray** [comment]
I have resolved this... just needed to sync

**Comment by MeissnerDa** [comment]
Hello @danieray ,
I am glad you could resolve your problem.

Best regards,
meissnerDa
