### ISSUE TITLE
AD - synced to wordpress but login failed

### ISSUE THREAD

**Issue by LVmetric** [NeosIT/active-directory-integration2#72]
Hi,

I've installed the plugin on two sites, one an 'intranet' (using Woffice theme) which is working perfectly and now with an 'extranet' (using KnowledgeBase theme) which syncs with WordPress but when I log in using an AD login it says the password is incorrect. 

I saw a similar problem on another issue raised and it was suggested that maybe the theme was incompatible with the plugin? Please can you confirm if it is compatible with KnowledgeBase?

Many thanks :-)

**Comment by MeissnerDa** [comment]
Hello @LVmetric ,
sorry but we can not confirm that NADI is compatible with the KnowledgeBase theme. Since the theme is not open source or has a free trial we do not have the possibility to test it. 

Best regards,
meissnerDa

**Comment by LVmetric** [comment]
Thank you for your prompt response.
