### ISSUE TITLE
Password sent in plaintext over STARTTLS connection

### ISSUE THREAD

**Issue by dmwhite823** [NeosIT/active-directory-integration2#73]
Environment:
Ubuntu 16.04, 
PHP 7.0.25,
WordPress 4.9.4,
NADI Plugin: 2.1.1,
AD: Server 2012

I am troubleshooting connectivity issues with our AD server. Using this plugin, WordPress authentication works fine when I'm not using any encryption.

Today, I went into NADI's configuration, and under the Environment tab, changed the encryption type to use STARTTLS. I have the Enable "Test Authentication" setting on the Profile tab turned on, so after making the above change, I navigated over to my Test authentication screen.

I entered valid credentials and clicked "Try to authenticate". At this point, the screen hangs indefinitely.

In troubleshooting why the test hangs, I ran a "tcpdump -vv port 389 -w filename.pcap" from the server while I then tried to run a test authentication, and then examined the pcap file.

From the time I started the packet capture (before clicking the "Try to authenticate" button to the time that the authentication page hangs), I only got 26 packets. 

As I was examining those packets in Wireshark, I noticed towards the end of the tcp stream that Wireshark had an "Ignored Unknown Record" entry on the TLSv1.2 protocol. I examined that packet further, and found that my username and password had been transmitted in clear text.

This is an issue. 

Tailing the nadi-debug.log file, I do see that successfully Checked "address my.domain.com and port 389 - OK". When the test page hangs, the last line in the nadi-debug.log file has the entry: "Trying to authenticate user with username 'my-user' and account suffix '@my.domain.com'

**Comment by dmwhite823** [comment]
Ok, here's some more information for you.

The issue when the Test AD authentication hangs indefinitely is my issue. That isn't an issue with the plugin. I have now been able to (inconsistently) successfully test AD authentication. I believe my issue is related to some firewall rules or some sort of network issue.

Additionally, I can confirm that my password is fully encrypted on the TLS handshake when (and only when) the authentication attempt is successful.

However, running a packet capture when the authentication attempt test hangs indefinitely, I can confirm that my password is sent in clear text. 

That is concerning to me, although now that I have successfully grabbed a packet capture when I successfully authenticated against AD, it's not quite as big of an issue as I first suspected - so that's good news!

**Comment by MeissnerDa** [comment]
Hello @dmwhite823,

Thank you for this detailed report. I will add this to our internal issue tracker and we will take a look at it. 

Best regards,
meissnerDa

**Comment by schakko** [comment]
Hi @dmwhite823, thank you for this report. I agree with you that it looks like some issues with your firewall/NAT rules. NADI itself does not implement any TLS protocol but uses the implementation PHP (OpenSSL) provides.

**Comment by dmwhite823** [comment]
I think that this issue can be reasonably closed now.
