### ISSUE TITLE
Incorrect Password

### ISSUE THREAD

**Issue by Tau175336** [NeosIT/active-directory-integration2#77]
Using Wordpress within WPEngine.  I am successfully able to Sync users to Wordpress.  I am successfully able to use the "Test Authentication".  However when attempting to login using a Synced user account I am receiving the error message "The Password you entered is incorrect".  

The nadi-debug log shows:
2018-04-18 17:54:05 [DEBUG] NextADInt_Adi_Authentication_SingleSignOn_Service::findUsername [line 234] SSO provided username for environment variable "REMOTE_USER" is "'

2018-04-18 17:54:05 [WARNING] NextADInt_Adi_Authentication_SingleSignOn_Service::authenticate [line 77] Cannot find username for SSO.

Any help would be appreciated.

**Comment by MeissnerDa** [comment]
Hello @Tau175336,

as I wrote you in the emails, this problem occurs because your login page is modified by a WordPress theme and therefore the NADI authentication hook is not registered on the login page.

Best regards,
meissnerDa

**Comment by codehaiku** [comment]
Hi, @MeissnerDa 

Most of themes/plugins use wp_login_form() function to display a login form in any part of their wp site. Does NADI work with forms rendered using wp_login_form()? Can you let us know what are those NADI authentication hooks so we can add support to our theme and plugins?

Thanks!

**Comment by brunomac** [comment]
Please, any feedback....
