### ISSUE TITLE
Probleme with AD and ldaps

### ISSUE THREAD

**Issue by bidule69** [NeosIT/active-directory-integration2#78]
Hello i got a problem when configuring ldaps on WordPress.
I'm able to configure and test ldap on port 389 with no problem
I'm also able to configure and test startTLS on port 636 with no problem.

But when i try to configure ldap on port 636 i got this error in the log.

[ERROR] NextADInt_Ldap_Connection::connect [line 61] Creating adLDAP object failed. Bind to Active Directory failed. Either the LDAPs connection failed or the login credentials are incorrect. [AD: ] [AD error code: ]

Hope you can help me on this one !

Regards,

Stephane

**Comment by MeissnerDa** [comment]
Hello @bidule69 ,

it is not possible to use normal LDAP via port 636. Port 636 is ment to be used for encrypted connections. 

Best regards,
meissnerDa
