### ISSUE TITLE
Old multisite documentation?

### ISSUE THREAD

**Issue by klishb** [NeosIT/active-directory-integration2#86]
I'm finding multisite doesn't work as expected.  I made the settings that I wanted and saved it as "My NADI profile". I then applied that configuration to all sites, but they actually get those settings.

All else failed so I'm reading the multisite configuration documentation.  It references the General tab, but I don't have one and I don't see an option like what's being described on any tab.  Am I missing something?

On the tab "General" enable the checkbox for Is active
On the tab General disable the checkboxes for the menu entries

**Comment by MeissnerDa** [comment]
Hello @klishb,
could you please send me a link to the page referencing the "General" tab? 

Regarding the multisite configuration profiles. Please make sure you set the permission correctly. The permission has to be set to anything BUT "Blog admin sets the option value." 

Best regards,
Danny Meißner

**Comment by klishb** [comment]
https://active-directory-wp.com/docs/Configuration/Multisite_configuration/Common_use_cases.html

**Comment by MeissnerDa** [comment]
Hello @klishb,

I adjusted the documentation. Thank you for the information. 

Best regards,
meissnerDa
