### ISSUE TITLE
Pass the auth only if user has specified role?

### ISSUE THREAD

**Issue by Destabilizator** [NeosIT/active-directory-integration2#89]
When user logs in, I'd like to use his sAMAccountName + password to bind and then let him proceed only if he has eg. "cvutrolesb2=0:435" attribute, similar to PHP's:

$filter="(&(sAMAccountName=" . $username . ")(cvutrolesb2=0:435))";

Does your plugin directly support that or has some hooks that I could use to extend it with this behaviour?

Thanks!

**Comment by schakko** [comment]
@Destabilizator At the moment there is no hook available which you could use.

@MeissnerDa I'd suggest two hooks:
- *next_ad_int_auth_before_create_or_update_user(NextADInt_Adi_Authentication_Credentials $credentials, array $ldapAttributes) : boolean* (if false, leave createOrUpdateUser and return false to caller) in https://github.com/NeosIT/active-directory-integration2/blob/00cddc0309119d6a0aa931d711f5d2063e217834/classes/Adi/Authentication/LoginService.php#L591

- *next_ad_int_auth_after_create_or_update_user(NextADInt_Adi_Authentication_Credentials $credentials, $adiUser, WP_User $wpUser) : boolean|WP_User* in https://github.com/NeosIT/active-directory-integration2/blob/00cddc0309119d6a0aa931d711f5d2063e217834/classes/Adi/Authentication/LoginService.php#L614

**Comment by simply-fiete** [comment]
Hey @Destabilizator 
we have just release a new version 2.1.5. Part of the new release are 2 new hooks attached to the authentication process. 
Please [check our updated documentation](https://active-directory-wp.com/docs/API/Authentication.html) for a detailed description of those new hooks. We hope these are useful to you and we would also like to thank you for suggesting/asking for this feature.
