### ISSUE TITLE
Fatal error: Failed opening required

### ISSUE THREAD

**Issue by metaarts** [NeosIT/active-directory-integration2#9]
After I have enabled the plugin on the network, on the front page occurs following errors.

> Warning: require_once(library/Mobile_Detect.php): failed to open stream: No such file or directory in /srv/www/htdocs/phoenix-mu/functions.php on line 18 Fatal error: require_once(): Failed opening required 'library/Mobile_Detect.php' (include_path='.:/usr/share/php5:/usr/share/php5/PEAR') in /srv/www/htdocs/phoenix-mu/functions.php on line 18

The line `require_once(library/Mobile_Detect.php)` comes from my themes function. A interesting fact is, that these line should come from `/srv/www/htdocs/phoenix-mu/functions.php` (`/srv/www/htdocs/phoenix-mu` is my WP root) Here ist the path from root to my theme missing . Why?

Without the plugin the theme works again.

**Comment by schakko** [comment]
Have you tried to include the *Mobile_Detect.php* with
   
    require_once(ABSPATH . '/library/Mobile_Detect.php');

At the moment I do not see the reason why this could error could happen. Can you provide your theme as download so we can debug it?

**Comment by metaarts** [comment]
I tried the absolute path for the `Mobile_Detect.php`. It don't work. I think our theme cause that problem. I will switch back to V.1 which worked.

Thank you for the offer to debug our theme but due to the projects security policies i am not allowed to bring any code outside. 

Maybe you can help me out with following problem I have (and thats why I tried the the V2): We have a single WP blog with like 1000 User added over the active directory integration. Now we want to serve a second WP blog which users from the first blog can easily access to the second blog, without to reregister. 

For that, we tried to import the first blog into a WP Multisite and build the second one. Due the import, all user from the old single blog are recognised as user in the first blog from the multisite. Because we want to share existing user to all our blogs, we need a logic to do that. Actually if a existing user from blog-1 tried to access to blog-2, the user will be redirect to the first blog.

Yes, from the backend we can assignee an existing user to the second blog. But this is a painful job, 'cause we have thousands of user which need to be moved and wordpress do not bring a "bulk" edit modus. And we need it automatically because of the amount of user which daily register.

Maybe there is a nice coded Plugin outside I didn't found you can share or you guys did this process in your V.2.

Thanks a lot!

Stavros

PS: I know that above has not have to do anymore with my initial Problem, so sorry for that ;)

**Comment by Tobi823** [comment]
I can not reproduce the bug with your theme. I wrote my own theme for debugging but i could not reproduce it.
We do not support ADI 1.1.8 any more, but I wrote a script for you.
This script will add all users from blog1 to blog2, blog3 ...
I suppose that ADI 1.1.8 can not update the roles of these copied user, so you have to run this script more than once.

```
<?php
/*
Plugin Name: Workaround active-directory-integration-1 #9
*/

add_action('wp_loaded', 'adi_v1_workaround_gh9');

function adi_v1_workaround_gh9() {
   $users = get_users(array('blog_id' => 1));
   $sites = wp_get_sites();

   foreach ($sites as $site) {
       $blog_id = intval($site['blog_id']);
       if ($blog_id == 1) {
           continue;
       }

       foreach ($users as $user) {
           $user_id = $user->ID;
           $role = $user->roles[0];
           
           $object = add_user_to_blog($blog_id, $user_id , $role);

           if (is_wp_error($object)) {
               echo $object;
           } else {
               echo "add user " . $user->display_name . " to blog "
                   . $site['blog_id'] . " with role " . $user->roles[0]
                   . '<br>';
           }

           restore_current_blog();
       }
   }
}
```


Please make a ​*backup*​ of your WordPress database before you execute this plugin.
