### ISSUE TITLE
Problem with sync to AD

### ISSUE THREAD

**Issue by miquelangeld** [NeosIT/active-directory-integration2#90]
I'm trying to change some attribute and then syncback to AD and I get this message:
`2018-10-16 08:39:48 [WARNING] NextADInt_Ldap_Connection::modifyUserWithoutSchema [line 495] Modifying user 'madaniel' skipped. Found no attributes to synchronize to Active Directory.
`

**Comment by schakko** [comment]
You have to map the attributes and check the "Sync to AD" option: http://active-directory-wp.com/docs/Configuration/Attributes.html
