### ISSUE TITLE
Automatic user creation = off

### ISSUE THREAD

**Issue by J-f-rey** [NeosIT/active-directory-integration2#91]
Hi, we have a 'little' problem setting up our LDAP connection.

Only with the option 'Automatic user creation' enabled we can login. But we DON'T want to add the users from our AD to WordPress.
In your 'getting started' guide (https://active-directory-wp.com/docs/Configuration/User.html) you say that for security reasons it's best turned off.

But what do we do wrong if turning this option to ON it's loggin in, but when turned OFF it doesn't?

**Comment by kokarn** [comment]
Having the same issue, login only works with that specific setting enabled.

**Comment by schakko** [comment]
This option will be removed with 2.4 (see #134) as it has never been intended to be working with NADI 2.x ;-)
