### ISSUE TITLE
Authorization groups not working

### ISSUE THREAD

**Issue by pokertour** [NeosIT/active-directory-integration2#92]
When using the “Authorization Groups” options in the “Permissions” tab, all users under the base DN are still able to login. This behavior wasn’t observed until the last update.

**Comment by schakko** [comment]
@pokertour thank you for this report, I have just added the issue to our internal tracker (ID ADI-664). See also https://wordpress.org/support/topic/authorization-groups-not-working/

**Comment by simply-fiete** [comment]
Hey @pokertour 
we have just release a new version. The update 2.1.5 contains a fix for the authorization group issue you have reported. 
Please update your plugin to the latest version. Thanks again for reporting this issue.
