### ISSUE TITLE
Sync To WordPress Problem

### ISSUE THREAD

**Issue by emilzawislak** [NeosIT/active-directory-integration2#93]
I have a problem with sync from AD. 
Domain SID | Verification successful!

> SID of user 'emilzawislak@tankgaz' could not be retrieved. Is the base DN correct? Does the userPrincipalName 'emilzawislak@tankgaz' exist and not only its sAMAccountName?'

**Comment by schakko** [comment]
Please check your *Base DN* attribute in *Environment*. Authentication does not mean that the user can be synchronized.
