### ISSUE TITLE
Can not login from my website

### ISSUE THREAD

**Issue by yaswad** [NeosIT/active-directory-integration2#94]
Hello: 

when I login to my site, I have to type the username@domain, is there a way to make it where the username is accepted without adding "@domain"? 

Also, I have a group in AC called "Special" which has admin right, can I have it configured where members of that group gets administrator role when signing in on wordpress site? 

Thank you,
Y

**Comment by schakko** [comment]
1. You can use the *Account suffix* feature: http://active-directory-wp.com/docs/Configuration/User.html
2. You can use Role equivalent groups: http://active-directory-wp.com/docs/Configuration/Permissions.html
