### ISSUE TITLE
some user don't syncing firstname lastname

### ISSUE THREAD

**Issue by pokertour** [NeosIT/active-directory-integration2#96]
Hello,

somes of my user don't get their firstname and lastname syncing with their wordpress profile
![image](https://user-images.githubusercontent.com/7757451/49855557-eec89780-fded-11e8-931f-8b17b1a28aa2.png)

and other user get their firstname and lastname 
![image](https://user-images.githubusercontent.com/7757451/49855610-0ef85680-fdee-11e8-974e-edfda45f2c25.png)

i use the last version of NADI 2.1.5, do you have any idea ?

**Comment by pokertour** [comment]
thx for your reply,

i just checked and this is my last sync for this user 
`2018-12-12 03:14:36 [DEBUG] NextADInt_Adi_User_Manager::updateUserMetaDataFromActiveDirectory [line 476] Set AD attribute 'cn' (ADI Attribute next_ad_int_cn={type='string', syncable='', viewable='', overwriteWithEmpty='}) to Yveline Renaud
2018-12-12 03:14:36 [DEBUG] NextADInt_Adi_User_Manager::updateUserMetaDataFromActiveDirectory [line 476] Set AD attribute 'givenname' (ADI Attribute next_ad_int_givenname={type='string', syncable='', viewable='', overwriteWithEmpty='}) to Yveline
2018-12-12 03:14:36 [DEBUG] NextADInt_Adi_User_Manager::updateUserMetaDataFromActiveDirectory [line 476] Set AD attribute 'sn' (ADI Attribute next_ad_int_sn={type='string', syncable='', viewable='', overwriteWithEmpty='}) to RENAUD`

**Comment by pokertour** [comment]
this is the last line of my log file : 

`2018-12-12 08:20:58 [INFO] NextADInt_Adi_Synchronization_WordPress::finishSynchronization [line 592] 0 users have been added to the WordPress database.`
`2018-12-12 08:20:58 [INFO] NextADInt_Adi_Synchronization_WordPress::finishSynchronization [line 593] 91 users from the WordPress database have been updated.`
`2018-12-12 08:20:58 [INFO] NextADInt_Adi_Synchronization_WordPress::finishSynchronization [line 594] 0 users could not be synchronized.`

So it's seeam that 12 users have disappear :D from the sync

**Comment by simply-fiete** [comment]
The synchronisation appears to be fine. The sync result also matches the expected format.
The number of the total synced users should stay the same between the synchronisations though.

Are you using any other plugins related to Active-Directory-Integration2 (premium extensions)?

**Comment by pokertour** [comment]
no i don't use any other plugins related to Active Directory

**Comment by simply-fiete** [comment]
I'll look into the issue and report back to you. I have also created an issue inside our internal issue tracker (ADI-667).

**Comment by pokertour** [comment]
Thx you @simply-fiete

**Comment by simply-fiete** [comment]
Hey @pokertour 
do you have access to the WordPress database?

I would like to know if the user attributes are inside the user_meta table.
Try executing the following SQL statement:
`
SELECT * FROM wp_usermeta WHERE meta_key = "next_ad_int_sn" AND meta_value = "RENAUD";
`
This should in theory return the matching entry.

**Comment by pokertour** [comment]
yes i got the entry : 
![image](https://user-images.githubusercontent.com/7757451/49861952-576b4080-fdfd-11e8-9005-b4f8e058e068.png)

**Comment by simply-fiete** [comment]
So this tells me the user has been imported/synced properly. 

I suspect there is an issue displaying the data. Do you use any custom themes?

**Comment by pokertour** [comment]
i use Woffice theme for the front-end

**Comment by pokertour** [comment]
this is what i got 
![image](https://user-images.githubusercontent.com/7757451/49863932-a915ca00-fe01-11e8-9f68-794222b02e9a.png)

**Comment by simply-fiete** [comment]
Ok @pokertour I might have discovered the problem:
The _first_name_ and _last_name_ attributes are both empty! Those are used to display the data inside the users profile.
I don't know why this is happening but I'll look into the issue!

**Comment by simply-fiete** [comment]
@pokertour can you please check if the user in question is being synced when you run a new synchronisation? 
I suspect the user is not being synced anymore due to missing groups or similar. This would also explain the 12 disappearing users between syncs.

The user is not being updated so this has to do with the sync not including the user. The first and last name might have been deleted manually inside the users profile.

**Comment by pokertour** [comment]
after sync AD to wordpress : 
![image](https://user-images.githubusercontent.com/7757451/49870182-edf62c80-fe12-11e8-9dd5-0cdca68231dd.png)

the user is not syncing

**Comment by pokertour** [comment]
ok, i've ask the user to login and now the firstname and lastname is here and the sync work for this user
![image](https://user-images.githubusercontent.com/7757451/49870282-34e42200-fe13-11e8-9d4f-f7a6deab255c.png)
![image](https://user-images.githubusercontent.com/7757451/49870364-6fe65580-fe13-11e8-8524-94e6bcf43418.png)

**Comment by simply-fiete** [comment]
@pokertour I will close this issue as your issue seems to have been resolved.
