### ISSUE TITLE
Sync To Wordpress button disabled

### ISSUE THREAD

**Issue by richk70** [NeosIT/active-directory-integration2#97]
On the Sync to Wordpress tab, the "Start AD to Wordpress synchronization" button is dimmed and unclickable. There's also a warning box that says "Check that a connection to a domain controller is established and 'Enable sync to WordPress' is checked. Also, a service account has to be provided."

So I checked those things:

1) Under Configuration > Profile, "Enable Sync to Wordpress" is checked

2) Under Configuration > Environment, I entered username & password and verify worked (when I go off of and then back to this tab, the username & password fields are blanked out...is this normal? Also, under Domain SID, I see "Wordpress site is currently connected to Domain: S-x-x-xx-xxxxxxx."

3) Under Test authentication, I entered my personal domain account and it worked.

Seems like everything is successfully connected to our AD, why is the sync button disabled?

Also, under Configuration > Sync to Wordpress, I left the Service account password field blank because the plugin documentation said "This option defines a NEW password for the Sync to WordPress service account. Leave this field blank if you don't want to change the current password."  I don't want to change the current service account password, so I followed the directions and left it blank.

Lastly, I tried to execute the sync via curl and got these error messages:
[ERROR] NextADInt_Ldap_Connection::checkConnection [line 323] Connection with AD failed. User: "ads.agent@blahblah" could not be authenticated against the AD.

Environment details:
Ubuntu Server 18.04 LTS
Apache 2.4.29
PHP 7.2.10
Wordpress 5.0.2
NADI 2.1.7
php-ldap php-mbstring are installed, openssl 1.1.0g came with php7.2

**Comment by schakko** [comment]
@richk70 I have clarified the documentation to 

> In order for importing multiple users at once you have to add an Active Directory service account with read permission in the AD. Please enter the full user information __including__ the domain suffix. The option *User Append suffix* has __no__ influence on this option.

>The *Service account username* and *Service account password* are the credentials for your *Sync to WordPress service account* and will be stored inside WordPress' database.

I hope, this makes it more clear that you **have** to enter a service account username and password inside the *Sync to WordPress* tab.

**Comment by richk70** [comment]
Thanks for letting me know the documentation was incorrect.  However, the documentation still says the old wrong thing.

https://active-directory-wp.com/docs/Configuration/Sync_to_WordPress.html

SERVICE ACCOUNT PASSWORD
This option defines a NEW password for the Sync to WordPress service account. Leave this field blank if you don't want to change the current password.

This contradicts what you say in the Service Account Username section, and should be corrected as well.
