### ISSUE TITLE
Media libary upload files 401

### ISSUE THREAD

**Issue by christianostrem** [NeosIT/active-directory-integration2#98]
Hi, I have trubble uploading files after using the plugin.
I get a 401 error when i try to upload.
Iam Using window server with apache, mariadb, ntml mod and IE 11

Vhost config.
<VirtualHost *:80>
	ServerName ?
	ServerAlias localhost
	DocumentRoot "c:/wamp64/sites/?/htdocs"
	<Directory  "c:/wamp64/sites/?/htdocs/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require all granted
	</Directory>
<Location / >
	AuthName "WordPress"
	AuthType SSPI
	NTLMAuth On
	NTLMAuthoritative On
	<RequireAll>
		<RequireAny>
			Require valid-user
			# ensure a non-existing user can't login
			# Require sspi-user domain\invalid
		</RequireAny>
	</RequireAll>
</Location>
</VirtualHost>

Do you have any ideas on how to fix this issue? or is it a bug?

**Comment by simply-fiete** [comment]
Hey @christianostrem,
this does not seem to be related to the NADI plugin itself. Our plugin does not interfere with the media upload.
Can you please disable the NADI plugin and try to upload an image? Does the issue persist?

**Comment by schakko** [comment]
@christianostrem Thank you for the response! Then it seems to be related to https://github.com/glpi-project/glpi/issues/594.
As you are on Windows, you can try to switch from mod_ntlm to mod_authn_ntlm (https://active-directory-wp.com/docs/Networking/Single_Sign_On/NTLM_SSO_with_Apache_on_Windows.html).
